#ifndef TIMING_H
#define TIMING_H

typedef double real_Double_t;

enum iparam_timing {
  TIMING_CHECK,
  TIMING_WARMUP,
  TIMING_NITER,
  TIMING_N,
  TIMING_M,
  TIMING_NB,
  /*TIMING_MB,*/
  TIMING_IB,
  TIMING_NRHS,
  TIMING_THRDNBR,
  TIMING_NCUDAS,
  TIMING_THRDNBR_SUBGRP,
  TIMING_SCHEDULER,
  TIMING_AUTOTUNING,
  TIMING_INPUTFMT,
  TIMING_OUTPUTFMT,
  TIMING_NDOM,
  /* Added for StarPU version */
  TIMING_PROFILE,
  TIMING_PEAK,
  TIMING_ITER,
  TIMING_PARALLEL_TASKS,
  TIMING_NO_CPU,
  TIMING_BOUND,
  TIMING_BOUNDDEPS,
  TIMING_BOUNDDEPSPRIO,
  /* End */
  TIMING_INBPARAM
};

enum dparam_timing {
  TIMING_TIME,
  TIMING_ANORM,
  TIMING_BNORM,
  TIMING_XNORM,
  TIMING_RES,
  TIMING_ESTIMATED_PEAK,
  TIMING_DNBPARAM
};

#endif /* TIMING_H */
