/*******************************************************************************
 *  This file is AUTOMATICALLY GENERATED by:
 *  ../tools/fortran_wrappers.pl --wrappers ../include/magma_z.h
 *  Do not edit.
 ******************************************************************************/

#include <stdint.h>  // for uintptr_t

#include "magma.h"

/*
 * typedef comming from fortran.h file provided in CUDADIR/src directory
 * it will probably change with future release of CUDA when they use 64 bit addresses
 */
typedef size_t devptr_t;

#ifdef PGI_FORTRAN
    #define magma_idevptr(ptr_) ((int*)               (ptr_))
    #define magma_zdevptr(ptr_) ((magmaDoubleComplex*)(ptr_))
    #ifndef magma_cdevptr
    #define magma_cdevptr(ptr_) ((magmaFloatComplex*) (ptr_))
    #endif
    #ifndef magma_ddevptr
    #define magma_ddevptr(ptr_) ((double*)            (ptr_))
    #endif
    #ifndef magma_sdevptr
    #define magma_sdevptr(ptr_) ((float*)             (ptr_))
    #endif
#else
    #define magma_idevptr(ptr_) ((int*)               (uintptr_t)(*(ptr_)))
    #define magma_zdevptr(ptr_) ((magmaDoubleComplex*)(uintptr_t)(*(ptr_)))
    #ifndef magma_cdevptr
    #define magma_cdevptr(ptr_) ((magmaFloatComplex*) (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_ddevptr
    #define magma_ddevptr(ptr_) ((double*)            (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_sdevptr
    #define magma_sdevptr(ptr_) ((float*)             (uintptr_t)(*(ptr_)))
    #endif
#endif

#ifndef MAGMA_FORTRAN_NAME
#if defined(ADD_)
#define MAGMA_FORTRAN_NAME(lcname, UCNAME)  magmaf_##lcname##_
#elif defined(NOCHANGE)
#define MAGMA_FORTRAN_NAME(lcname, UCNAME)  magmaf_##lcname
#elif defined(UPCASE)
#define MAGMA_FORTRAN_NAME(lcname, UCNAME)  MAGMAF_##UCNAME
#endif
#endif

#ifndef MAGMA_GPU_FORTRAN_NAME
#if defined(ADD_)
#define MAGMA_GPU_FORTRAN_NAME(lcname, UCNAME)  magmaf_##lcname##_gpu_
#elif defined(NOCHANGE)
#define MAGMA_GPU_FORTRAN_NAME(lcname, UCNAME)  magmaf_##lcname##_gpu
#elif defined(UPCASE)
#define MAGMA_GPU_FORTRAN_NAME(lcname, UCNAME)  MAGMAF_##UCNAME##_GPU
#endif
#endif

#define PRECISION_z

#ifdef __cplusplus
extern "C" {
#endif

/*
    -- MAGMA (version 1.1) --
       Univ. of Tennessee, Knoxville
       Univ. of California, Berkeley
       Univ. of Colorado, Denver
       November 2011

       @precisions normal z -> s d c
*/





/* ////////////////////////////////////////////////////////////////////////////
   -- MAGMA Auxiliary functions to get the NB used
*/
#define magmaf_get_zpotrf_nb MAGMA_FORTRAN_NAME( get_zpotrf_nb, GET_ZPOTRF_NB )
magma_int_t magmaf_get_zpotrf_nb( magma_int_t *m )
{
    return magma_get_zpotrf_nb( *m );
}

#define magmaf_get_zgetrf_nb MAGMA_FORTRAN_NAME( get_zgetrf_nb, GET_ZGETRF_NB )
magma_int_t magmaf_get_zgetrf_nb( magma_int_t *m )
{
    return magma_get_zgetrf_nb( *m );
}

#define magmaf_get_zgetri_nb MAGMA_FORTRAN_NAME( get_zgetri_nb, GET_ZGETRI_NB )
magma_int_t magmaf_get_zgetri_nb( magma_int_t *m )
{
    return magma_get_zgetri_nb( *m );
}

#define magmaf_get_zgeqp3_nb MAGMA_FORTRAN_NAME( get_zgeqp3_nb, GET_ZGEQP3_NB )
magma_int_t magmaf_get_zgeqp3_nb( magma_int_t *m )
{
    return magma_get_zgeqp3_nb( *m );
}

#define magmaf_get_zgeqrf_nb MAGMA_FORTRAN_NAME( get_zgeqrf_nb, GET_ZGEQRF_NB )
magma_int_t magmaf_get_zgeqrf_nb( magma_int_t *m )
{
    return magma_get_zgeqrf_nb( *m );
}

#define magmaf_get_zgeqlf_nb MAGMA_FORTRAN_NAME( get_zgeqlf_nb, GET_ZGEQLF_NB )
magma_int_t magmaf_get_zgeqlf_nb( magma_int_t *m )
{
    return magma_get_zgeqlf_nb( *m );
}

#define magmaf_get_zgehrd_nb MAGMA_FORTRAN_NAME( get_zgehrd_nb, GET_ZGEHRD_NB )
magma_int_t magmaf_get_zgehrd_nb( magma_int_t *m )
{
    return magma_get_zgehrd_nb( *m );
}

#define magmaf_get_zhetrd_nb MAGMA_FORTRAN_NAME( get_zhetrd_nb, GET_ZHETRD_NB )
magma_int_t magmaf_get_zhetrd_nb( magma_int_t *m )
{
    return magma_get_zhetrd_nb( *m );
}

#define magmaf_get_zgelqf_nb MAGMA_FORTRAN_NAME( get_zgelqf_nb, GET_ZGELQF_NB )
magma_int_t magmaf_get_zgelqf_nb( magma_int_t *m )
{
    return magma_get_zgelqf_nb( *m );
}

#define magmaf_get_zgebrd_nb MAGMA_FORTRAN_NAME( get_zgebrd_nb, GET_ZGEBRD_NB )
magma_int_t magmaf_get_zgebrd_nb( magma_int_t *m )
{
    return magma_get_zgebrd_nb( *m );
}

#define magmaf_get_zhegst_nb MAGMA_FORTRAN_NAME( get_zhegst_nb, GET_ZHEGST_NB )
magma_int_t magmaf_get_zhegst_nb( magma_int_t *m )
{
    return magma_get_zhegst_nb( *m );
}

#define magmaf_get_zgesvd_nb MAGMA_FORTRAN_NAME( get_zgesvd_nb, GET_ZGESVD_NB )
magma_int_t magmaf_get_zgesvd_nb( magma_int_t *m )
{
    return magma_get_zgesvd_nb( *m );
}

#define magmaf_get_zhegst_nb_m MAGMA_FORTRAN_NAME( get_zhegst_nb_m, GET_ZHEGST_NB_M )
magma_int_t magmaf_get_zhegst_nb_m( magma_int_t *m )
{
    return magma_get_zhegst_nb_m( *m );
}

#define magmaf_get_zbulge_nb MAGMA_FORTRAN_NAME( get_zbulge_nb, GET_ZBULGE_NB )
void magmaf_get_zbulge_nb(
    magma_int_t *m, magma_int_t *nbthreads )
{
    magma_get_zbulge_nb(
        *m, *nbthreads );
}

#define magmaf_zbulge_get_Vblksiz MAGMA_FORTRAN_NAME( zbulge_get_Vblksiz, ZBULGE_GET_VBLKSIZ )
void magmaf_zbulge_get_Vblksiz(
    magma_int_t *m, magma_int_t *nb, magma_int_t *nbthreads )
{
    magma_zbulge_get_Vblksiz(
        *m, *nb, *nbthreads );
}

#define magmaf_get_zbulge_gcperf MAGMA_FORTRAN_NAME( get_zbulge_gcperf, GET_ZBULGE_GCPERF )
void magmaf_get_zbulge_gcperf(
     )
{
    magma_get_zbulge_gcperf(
         );
}

// define this only once
#if defined(PRECISION_d)
#define magmaf_get_smlsize_divideconquer MAGMA_FORTRAN_NAME( get_smlsize_divideconquer, GET_SMLSIZE_DIVIDECONQUER )
void magmaf_get_smlsize_divideconquer(
     )
{
    magma_get_smlsize_divideconquer(
         );
}

#endif

/* ////////////////////////////////////////////////////////////////////////////
   -- MAGMA function definitions / Data on CPU
*/
#if defined(PRECISION_d) || defined(PRECISION_s)
#define magmaf_dmove_eig MAGMA_FORTRAN_NAME( dmove_eig, DMOVE_EIG )
void magmaf_dmove_eig(
    char *range, magma_int_t *n,
    double *w,
    magma_int_t *il,
    magma_int_t *iu, double *vl, double *vu,
    magma_int_t *m )
{
    magma_dmove_eig(
        *range, *n,
        w,
        il,
        iu, *vl, *vu,
        m );
}

#endif

#define magmaf_zgebrd MAGMA_FORTRAN_NAME( zgebrd, ZGEBRD )
void magmaf_zgebrd(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    double *d,
    double *e,
    magmaDoubleComplex *tauq,
    magmaDoubleComplex *taup,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgebrd(
        *m, *n,
        A, *lda,
        d,
        e,
        tauq,
        taup,
        work, *lwork,
        info );
}

#define magmaf_zgehrd2 MAGMA_FORTRAN_NAME( zgehrd2, ZGEHRD2 )
void magmaf_zgehrd2(
    magma_int_t *n, magma_int_t *ilo, magma_int_t *ihi,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgehrd2(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgehrd MAGMA_FORTRAN_NAME( zgehrd, ZGEHRD )
void magmaf_zgehrd(
    magma_int_t *n, magma_int_t *ilo, magma_int_t *ihi,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    devptr_t *dT,
    magma_int_t *info )
{
    magma_zgehrd(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        magma_zdevptr(dT),
        info );
}

#define magmaf_zgelqf MAGMA_FORTRAN_NAME( zgelqf, ZGELQF )
void magmaf_zgelqf(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgelqf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgeqlf MAGMA_FORTRAN_NAME( zgeqlf, ZGEQLF )
void magmaf_zgeqlf(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqlf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgeqrf MAGMA_FORTRAN_NAME( zgeqrf, ZGEQRF )
void magmaf_zgeqrf(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqrf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgeqrf4 MAGMA_FORTRAN_NAME( zgeqrf4, ZGEQRF4 )
void magmaf_zgeqrf4(
    magma_int_t *num_gpus, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqrf4(
        *num_gpus, *m, *n,
        a, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgeqrf_ooc MAGMA_FORTRAN_NAME( zgeqrf_ooc, ZGEQRF_OOC )
void magmaf_zgeqrf_ooc(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqrf_ooc(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgesv MAGMA_FORTRAN_NAME( zgesv, ZGESV )
void magmaf_zgesv(
    magma_int_t *n, magma_int_t *nrhs,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *ipiv,
    magmaDoubleComplex *B, magma_int_t *ldb,
    magma_int_t *info )
{
    magma_zgesv(
        *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magmaf_zgetrf MAGMA_FORTRAN_NAME( zgetrf, ZGETRF )
void magmaf_zgetrf(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *ipiv,
    magma_int_t *info )
{
    magma_zgetrf(
        *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magmaf_zposv MAGMA_FORTRAN_NAME( zposv, ZPOSV )
void magmaf_zposv(
    char *uplo, magma_int_t *n, magma_int_t *nrhs,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *B, magma_int_t *ldb,
    magma_int_t *info )
{
    magma_zposv(
        *uplo, *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magmaf_zpotrf MAGMA_FORTRAN_NAME( zpotrf, ZPOTRF )
void magmaf_zpotrf(
    char *uplo, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *info )
{
    magma_zpotrf(
        *uplo, *n,
        A, *lda,
        info );
}

#define magmaf_zpotri MAGMA_FORTRAN_NAME( zpotri, ZPOTRI )
void magmaf_zpotri(
    char *uplo, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *info )
{
    magma_zpotri(
        *uplo, *n,
        A, *lda,
        info );
}

#define magmaf_zlauum MAGMA_FORTRAN_NAME( zlauum, ZLAUUM )
void magmaf_zlauum(
    char *uplo, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *info )
{
    magma_zlauum(
        *uplo, *n,
        A, *lda,
        info );
}

#define magmaf_ztrtri MAGMA_FORTRAN_NAME( ztrtri, ZTRTRI )
void magmaf_ztrtri(
    char *uplo, char *diag, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *info )
{
    magma_ztrtri(
        *uplo, *diag, *n,
        A, *lda,
        info );
}

#define magmaf_zhetrd MAGMA_FORTRAN_NAME( zhetrd, ZHETRD )
void magmaf_zhetrd(
    char *uplo, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    double *d,
    double *e,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zhetrd(
        *uplo, *n,
        A, *lda,
        d,
        e,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zungqr MAGMA_FORTRAN_NAME( zungqr, ZUNGQR )
void magmaf_zungqr(
    magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    devptr_t *dT, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zungqr(
        *m, *n, *k,
        a, *lda,
        tau,
        magma_zdevptr(dT), *nb,
        info );
}

#define magmaf_zungqr2 MAGMA_FORTRAN_NAME( zungqr2, ZUNGQR2 )
void magmaf_zungqr2(
    magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magma_int_t *info )
{
    magma_zungqr2(
        *m, *n, *k,
        a, *lda,
        tau,
        info );
}

#define magmaf_zunmql MAGMA_FORTRAN_NAME( zunmql, ZUNMQL )
void magmaf_zunmql(
    char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zunmql(
        *side, *trans, *m, *n, *k,
        a, *lda,
        tau,
        c, *ldc,
        work, *lwork,
        info );
}

#define magmaf_zunmqr MAGMA_FORTRAN_NAME( zunmqr, ZUNMQR )
void magmaf_zunmqr(
    char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zunmqr(
        *side, *trans, *m, *n, *k,
        a, *lda,
        tau,
        c, *ldc,
        work, *lwork,
        info );
}

#define magmaf_zunmtr MAGMA_FORTRAN_NAME( zunmtr, ZUNMTR )
void magmaf_zunmtr(
    char *side, char *uplo, char *trans, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zunmtr(
        *side, *uplo, *trans, *m, *n,
        a, *lda,
        tau,
        c, *ldc,
        work, *lwork,
        info );
}

#define magmaf_zunghr MAGMA_FORTRAN_NAME( zunghr, ZUNGHR )
void magmaf_zunghr(
    magma_int_t *n, magma_int_t *ilo, magma_int_t *ihi,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    devptr_t *dT, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zunghr(
        *n, *ilo, *ihi,
        a, *lda,
        tau,
        magma_zdevptr(dT), *nb,
        info );
}

#if defined(PRECISION_z) || defined(PRECISION_c)
#define magmaf_zgeev MAGMA_FORTRAN_NAME( zgeev, ZGEEV )
void magmaf_zgeev(
    char *jobvl, char *jobvr, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *w,
    magmaDoubleComplex *vl, magma_int_t *ldvl,
    magmaDoubleComplex *vr, magma_int_t *ldvr,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *info )
{
    magma_zgeev(
        *jobvl, *jobvr, *n,
        a, *lda,
        w,
        vl, *ldvl,
        vr, *ldvr,
        work, *lwork,
        rwork,
        info );
}

#define magmaf_zgeqp3 MAGMA_FORTRAN_NAME( zgeqp3, ZGEQP3 )
void magmaf_zgeqp3(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *info )
{
    magma_zgeqp3(
        *m, *n,
        a, *lda,
        jpvt,
        tau,
        work, *lwork,
        rwork,
        info );
}

#define magmaf_zgesvd MAGMA_FORTRAN_NAME( zgesvd, ZGESVD )
void magmaf_zgesvd(
    char *jobu, char *jobvt, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *s,
    magmaDoubleComplex *u, magma_int_t *ldu,
    magmaDoubleComplex *vt, magma_int_t *ldvt,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *info )
{
    magma_zgesvd(
        *jobu, *jobvt, *m, *n,
        a, *lda,
        s,
        u, *ldu,
        vt, *ldvt,
        work, *lwork,
        rwork,
        info );
}

#define magmaf_zheevd MAGMA_FORTRAN_NAME( zheevd, ZHEEVD )
void magmaf_zheevd(
    char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd(
        *jobz, *uplo, *n,
        a, *lda,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx MAGMA_FORTRAN_NAME( zheevdx, ZHEEVDX )
void magmaf_zheevdx(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_2stage MAGMA_FORTRAN_NAME( zheevdx_2stage, ZHEEVDX_2STAGE )
void magmaf_zheevdx_2stage(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_2stage(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevx MAGMA_FORTRAN_NAME( zheevx, ZHEEVX )
void magmaf_zheevx(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *z, magma_int_t *ldz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *iwork,
    magma_int_t *ifail,
    magma_int_t *info )
{
    magma_zheevx(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        z, *ldz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magmaf_zheevr MAGMA_FORTRAN_NAME( zheevr, ZHEEVR )
void magmaf_zheevr(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *z, magma_int_t *ldz,
    magma_int_t *isuppz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevr(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        z, *ldz,
        isuppz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvd MAGMA_FORTRAN_NAME( zhegvd, ZHEGVD )
void magmaf_zhegvd(
    magma_int_t *itype, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvd(
        *itype, *jobz, *uplo, *n,
        a, *lda,
        b, *ldb,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx MAGMA_FORTRAN_NAME( zhegvdx, ZHEGVDX )
void magmaf_zhegvdx(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_2stage MAGMA_FORTRAN_NAME( zhegvdx_2stage, ZHEGVDX_2STAGE )
void magmaf_zhegvdx_2stage(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_2stage(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvx MAGMA_FORTRAN_NAME( zhegvx, ZHEGVX )
void magmaf_zhegvx(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *z, magma_int_t *ldz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *iwork,
    magma_int_t *ifail,
    magma_int_t *info )
{
    magma_zhegvx(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        z, *ldz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magmaf_zhegvr MAGMA_FORTRAN_NAME( zhegvr, ZHEGVR )
void magmaf_zhegvr(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *z, magma_int_t *ldz,
    magma_int_t *isuppz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvr(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        z, *ldz,
        isuppz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zstedx MAGMA_FORTRAN_NAME( zstedx, ZSTEDX )
void magmaf_zstedx(
    char *range, magma_int_t *n, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    double *D,
    double *E,
    magmaDoubleComplex *Z, magma_int_t *ldz,
    double *rwork, magma_int_t *ldrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    double *dwork,
    magma_int_t *info )
{
    magma_zstedx(
        *range, *n, *vl, *vu, *il, *iu,
        D,
        E,
        Z, *ldz,
        rwork, *ldrwork,
        iwork, *liwork,
        dwork,
        info );
}

#else /* not (defined(PRECISION_z) || defined(PRECISION_c)) */

#define magmaf_zgeev MAGMA_FORTRAN_NAME( zgeev, ZGEEV )
void magmaf_zgeev(
    char *jobvl, char *jobvr, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *wr,
    magmaDoubleComplex *wi,
    magmaDoubleComplex *vl, magma_int_t *ldvl,
    magmaDoubleComplex *vr, magma_int_t *ldvr,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeev(
        *jobvl, *jobvr, *n,
        a, *lda,
        wr,
        wi,
        vl, *ldvl,
        vr, *ldvr,
        work, *lwork,
        info );
}

#define magmaf_zgeqp3 MAGMA_FORTRAN_NAME( zgeqp3, ZGEQP3 )
void magmaf_zgeqp3(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqp3(
        *m, *n,
        a, *lda,
        jpvt,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgesvd MAGMA_FORTRAN_NAME( zgesvd, ZGESVD )
void magmaf_zgesvd(
    char *jobu, char *jobvt, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *s,
    magmaDoubleComplex *u, magma_int_t *ldu,
    magmaDoubleComplex *vt, magma_int_t *ldvt,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgesvd(
        *jobu, *jobvt, *m, *n,
        a, *lda,
        s,
        u, *ldu,
        vt, *ldvt,
        work, *lwork,
        info );
}

#define magmaf_zheevd MAGMA_FORTRAN_NAME( zheevd, ZHEEVD )
void magmaf_zheevd(
    char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd(
        *jobz, *uplo, *n,
        a, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx MAGMA_FORTRAN_NAME( zheevdx, ZHEEVDX )
void magmaf_zheevdx(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_2stage MAGMA_FORTRAN_NAME( zheevdx_2stage, ZHEEVDX_2STAGE )
void magmaf_zheevdx_2stage(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_2stage(
        *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvd MAGMA_FORTRAN_NAME( zhegvd, ZHEGVD )
void magmaf_zhegvd(
    magma_int_t *itype, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvd(
        *itype, *jobz, *uplo, *n,
        a, *lda,
        b, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx MAGMA_FORTRAN_NAME( zhegvdx, ZHEGVDX )
void magmaf_zhegvdx(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_2stage MAGMA_FORTRAN_NAME( zhegvdx_2stage, ZHEGVDX_2STAGE )
void magmaf_zhegvdx_2stage(
    magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_2stage(
        *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zstedx MAGMA_FORTRAN_NAME( zstedx, ZSTEDX )
void magmaf_zstedx(
    char *range, magma_int_t *n, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    double *d,
    double *e,
    double *z, magma_int_t *ldz,
    double *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    double *dwork,
    magma_int_t *info )
{
    magma_zstedx(
        *range, *n, *vl, *vu, *il, *iu,
        d,
        e,
        z, *ldz,
        work, *lwork,
        iwork, *liwork,
        dwork,
        info );
}

#endif /* not (defined(PRECISION_z) || defined(PRECISION_c)) */

#define magmaf_zhegst MAGMA_FORTRAN_NAME( zhegst, ZHEGST )
void magmaf_zhegst(
    magma_int_t *itype, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    magma_int_t *info )
{
    magma_zhegst(
        *itype, *uplo, *n,
        a, *lda,
        b, *ldb,
        info );
}

/* ////////////////////////////////////////////////////////////////////////////
 -- MAGMA function definitions / Data on CPU / Multi-GPU
*/
#if defined(PRECISION_z) || defined(PRECISION_c)
#define magmaf_zgeev_m MAGMA_FORTRAN_NAME( zgeev_m, ZGEEV_M )
void magmaf_zgeev_m(
    char *jobvl, char *jobvr, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *W,
    magmaDoubleComplex *vl, magma_int_t *ldvl,
    magmaDoubleComplex *vr, magma_int_t *ldvr,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *info )
{
    magma_zgeev_m(
        *jobvl, *jobvr, *n,
        A, *lda,
        W,
        vl, *ldvl,
        vr, *ldvr,
        work, *lwork,
        rwork,
        info );
}

#else
#define magmaf_zgeev_m MAGMA_FORTRAN_NAME( zgeev_m, ZGEEV_M )
void magmaf_zgeev_m(
    char *jobvl, char *jobvr, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    double *WR,
    double *WI,
    magmaDoubleComplex *vl, magma_int_t *ldvl,
    magmaDoubleComplex *vr, magma_int_t *ldvr,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeev_m(
        *jobvl, *jobvr, *n,
        A, *lda,
        WR,
        WI,
        vl, *ldvl,
        vr, *ldvr,
        work, *lwork,
        info );
}

#endif

#define magmaf_zgehrd_m MAGMA_FORTRAN_NAME( zgehrd_m, ZGEHRD_M )
void magmaf_zgehrd_m(
    magma_int_t *n, magma_int_t *ilo, magma_int_t *ihi,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magmaDoubleComplex *T,
    magma_int_t *info )
{
    magma_zgehrd_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        T,
        info );
}

#define magmaf_zunghr_m MAGMA_FORTRAN_NAME( zunghr_m, ZUNGHR_M )
void magmaf_zunghr_m(
    magma_int_t *n, magma_int_t *ilo, magma_int_t *ihi,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *T, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zunghr_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magmaf_zungqr_m MAGMA_FORTRAN_NAME( zungqr_m, ZUNGQR_M )
void magmaf_zungqr_m(
    magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *A, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *T, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zungqr_m(
        *m, *n, *k,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magmaf_zpotrf_m MAGMA_FORTRAN_NAME( zpotrf_m, ZPOTRF_M )
void magmaf_zpotrf_m(
    magma_int_t *num_gpus, char *uplo, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *info )
{
    magma_zpotrf_m(
        *num_gpus, *uplo, *n,
        A, *lda,
        info );
}

#define magmaf_zstedx_m MAGMA_FORTRAN_NAME( zstedx_m, ZSTEDX_M )
void magmaf_zstedx_m(
    magma_int_t *nrgpu, char *range, magma_int_t *n, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    double *D,
    double *E,
    magmaDoubleComplex *Z, magma_int_t *ldz,
    double *rwork, magma_int_t *ldrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zstedx_m(
        *nrgpu, *range, *n, *vl, *vu, *il, *iu,
        D,
        E,
        Z, *ldz,
        rwork, *ldrwork,
        iwork, *liwork,
        info );
}

#define magmaf_ztrsm_m MAGMA_FORTRAN_NAME( ztrsm_m, ZTRSM_M )
void magmaf_ztrsm_m(
    magma_int_t *nrgpu, char *side, char *uplo, char *transa, char *diag, magma_int_t *m, magma_int_t *n, magmaDoubleComplex *alpha,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb )
{
    magma_ztrsm_m(
        *nrgpu, *side, *uplo, *transa, *diag, *m, *n, *alpha,
        a, *lda,
        b, *ldb );
}

#define magmaf_zunmqr_m MAGMA_FORTRAN_NAME( zunmqr_m, ZUNMQR_M )
void magmaf_zunmqr_m(
    magma_int_t *nrgpu, char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zunmqr_m(
        *nrgpu, *side, *trans, *m, *n, *k,
        a, *lda,
        tau,
        c, *ldc,
        work, *lwork,
        info );
}

#define magmaf_zunmtr_m MAGMA_FORTRAN_NAME( zunmtr_m, ZUNMTR_M )
void magmaf_zunmtr_m(
    magma_int_t *nrgpu, char *side, char *uplo, char *trans, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zunmtr_m(
        *nrgpu, *side, *uplo, *trans, *m, *n,
        a, *lda,
        tau,
        c, *ldc,
        work, *lwork,
        info );
}

#define magmaf_zhegst_m MAGMA_FORTRAN_NAME( zhegst_m, ZHEGST_M )
void magmaf_zhegst_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    magma_int_t *info )
{
    magma_zhegst_m(
        *nrgpu, *itype, *uplo, *n,
        a, *lda,
        b, *ldb,
        info );
}

#if defined(PRECISION_z) || defined(PRECISION_c)
#define magmaf_zheevd_m MAGMA_FORTRAN_NAME( zheevd_m, ZHEEVD_M )
void magmaf_zheevd_m(
    magma_int_t *nrgpu, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd_m(
        *nrgpu, *jobz, *uplo, *n,
        a, *lda,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvd_m MAGMA_FORTRAN_NAME( zhegvd_m, ZHEGVD_M )
void magmaf_zhegvd_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvd_m(
        *nrgpu, *itype, *jobz, *uplo, *n,
        a, *lda,
        b, *ldb,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_m MAGMA_FORTRAN_NAME( zheevdx_m, ZHEEVDX_M )
void magmaf_zheevdx_m(
    magma_int_t *nrgpu, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_m(
        *nrgpu, *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_m MAGMA_FORTRAN_NAME( zhegvdx_m, ZHEGVDX_M )
void magmaf_zhegvdx_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_m(
        *nrgpu, *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_2stage_m MAGMA_FORTRAN_NAME( zheevdx_2stage_m, ZHEEVDX_2STAGE_M )
void magmaf_zheevdx_2stage_m(
    magma_int_t *nrgpu, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_2stage_m(
        *nrgpu, *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_2stage_m MAGMA_FORTRAN_NAME( zhegvdx_2stage_m, ZHEGVDX_2STAGE_M )
void magmaf_zhegvdx_2stage_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_2stage_m(
        *nrgpu, *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#else /* not (defined(PRECISION_z) || defined(PRECISION_c)) */
#define magmaf_zheevd_m MAGMA_FORTRAN_NAME( zheevd_m, ZHEEVD_M )
void magmaf_zheevd_m(
    magma_int_t *nrgpu, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd_m(
        *nrgpu, *jobz, *uplo, *n,
        a, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvd_m MAGMA_FORTRAN_NAME( zhegvd_m, ZHEGVD_M )
void magmaf_zhegvd_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvd_m(
        *nrgpu, *itype, *jobz, *uplo, *n,
        a, *lda,
        b, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_m MAGMA_FORTRAN_NAME( zheevdx_m, ZHEEVDX_M )
void magmaf_zheevdx_m(
    magma_int_t *nrgpu, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_m(
        *nrgpu, *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_m MAGMA_FORTRAN_NAME( zhegvdx_m, ZHEGVDX_M )
void magmaf_zhegvdx_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_m(
        *nrgpu, *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_2stage_m MAGMA_FORTRAN_NAME( zheevdx_2stage_m, ZHEEVDX_2STAGE_M )
void magmaf_zheevdx_2stage_m(
    magma_int_t *nrgpu, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_2stage_m(
        *nrgpu, *jobz, *range, *uplo, *n,
        a, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zhegvdx_2stage_m MAGMA_FORTRAN_NAME( zhegvdx_2stage_m, ZHEGVDX_2STAGE_M )
void magmaf_zhegvdx_2stage_m(
    magma_int_t *nrgpu, magma_int_t *itype, char *jobz, char *range, char *uplo, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *b, magma_int_t *ldb, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zhegvdx_2stage_m(
        *nrgpu, *itype, *jobz, *range, *uplo, *n,
        a, *lda,
        b, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#endif


/* ////////////////////////////////////////////////////////////////////////////
 -- MAGMA function definitions / Data on GPU
*/
#define magmaf_zgels_gpu MAGMA_GPU_FORTRAN_NAME( zgels, ZGELS )
void magmaf_zgels_gpu(
    char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    devptr_t *dB, magma_int_t *lddb,
    magmaDoubleComplex *hwork, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgels_gpu(
        *trans, *m, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        magma_zdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magmaf_zgels3_gpu MAGMA_GPU_FORTRAN_NAME( zgels3, ZGELS3 )
void magmaf_zgels3_gpu(
    char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    devptr_t *dB, magma_int_t *lddb,
    magmaDoubleComplex *hwork, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgels3_gpu(
        *trans, *m, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        magma_zdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magmaf_zgelqf_gpu MAGMA_GPU_FORTRAN_NAME( zgelqf, ZGELQF )
void magmaf_zgelqf_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgelqf_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zgeqr2x_gpu MAGMA_GPU_FORTRAN_NAME( zgeqr2x, ZGEQR2X )
void magmaf_zgeqr2x_gpu(
    magma_int_t *m,
    magma_int_t *n,
    devptr_t *dA,
    magma_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_int_t *info )
{
    magma_zgeqr2x_gpu(
        m,
        n,
        magma_zdevptr(dA),
        ldda,
        magma_zdevptr(dtau),
        magma_zdevptr(dT),
        magma_zdevptr(ddA),
        magma_ddevptr(dwork),
        info );
}

#define magmaf_zgeqr2x2_gpu MAGMA_GPU_FORTRAN_NAME( zgeqr2x2, ZGEQR2X2 )
void magmaf_zgeqr2x2_gpu(
    magma_int_t *m,
    magma_int_t *n,
    devptr_t *dA,
    magma_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_int_t *info )
{
    magma_zgeqr2x2_gpu(
        m,
        n,
        magma_zdevptr(dA),
        ldda,
        magma_zdevptr(dtau),
        magma_zdevptr(dT),
        magma_zdevptr(ddA),
        magma_ddevptr(dwork),
        info );
}

#define magmaf_zgeqr2x3_gpu MAGMA_GPU_FORTRAN_NAME( zgeqr2x3, ZGEQR2X3 )
void magmaf_zgeqr2x3_gpu(
    magma_int_t *m,
    magma_int_t *n,
    devptr_t *dA,
    magma_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_int_t *info )
{
    magma_zgeqr2x3_gpu(
        m,
        n,
        magma_zdevptr(dA),
        ldda,
        magma_zdevptr(dtau),
        magma_zdevptr(dT),
        magma_zdevptr(ddA),
        magma_ddevptr(dwork),
        info );
}

#define magmaf_zgeqr2x4_gpu MAGMA_GPU_FORTRAN_NAME( zgeqr2x4, ZGEQR2X4 )
void magmaf_zgeqr2x4_gpu(
    magma_int_t *m,
    magma_int_t *n,
    devptr_t *dA,
    magma_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_int_t *info, magma_queue_t *stream )
{
    magma_zgeqr2x4_gpu(
        m,
        n,
        magma_zdevptr(dA),
        ldda,
        magma_zdevptr(dtau),
        magma_zdevptr(dT),
        magma_zdevptr(ddA),
        magma_ddevptr(dwork),
        info, *stream );
}

#define magmaf_zgeqrf_gpu MAGMA_GPU_FORTRAN_NAME( zgeqrf, ZGEQRF )
void magmaf_zgeqrf_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dT,
    magma_int_t *info )
{
    magma_zgeqrf_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        tau,
        magma_zdevptr(dT),
        info );
}

#define magmaf_zgeqrf2_gpu MAGMA_GPU_FORTRAN_NAME( zgeqrf2, ZGEQRF2 )
void magmaf_zgeqrf2_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    magma_int_t *info )
{
    magma_zgeqrf2_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        tau,
        info );
}

#define magmaf_zgeqrf3_gpu MAGMA_GPU_FORTRAN_NAME( zgeqrf3, ZGEQRF3 )
void magmaf_zgeqrf3_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dT,
    magma_int_t *info )
{
    magma_zgeqrf3_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        tau,
        magma_zdevptr(dT),
        info );
}

#define magmaf_zgeqrs_gpu MAGMA_GPU_FORTRAN_NAME( zgeqrs, ZGEQRS )
void magmaf_zgeqrs_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dT,
    devptr_t *dB, magma_int_t *lddb,
    magmaDoubleComplex *hwork, magma_int_t *lhwork,
    magma_int_t *info )
{
    magma_zgeqrs_gpu(
        *m, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        tau,
        magma_zdevptr(dT),
        magma_zdevptr(dB), *lddb,
        hwork, *lhwork,
        info );
}

#define magmaf_zgeqrs3_gpu MAGMA_GPU_FORTRAN_NAME( zgeqrs3, ZGEQRS3 )
void magmaf_zgeqrs3_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dT,
    devptr_t *dB, magma_int_t *lddb,
    magmaDoubleComplex *hwork, magma_int_t *lhwork,
    magma_int_t *info )
{
    magma_zgeqrs3_gpu(
        *m, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        tau,
        magma_zdevptr(dT),
        magma_zdevptr(dB), *lddb,
        hwork, *lhwork,
        info );
}

#define magmaf_zgessm_gpu MAGMA_GPU_FORTRAN_NAME( zgessm, ZGESSM )
void magmaf_zgessm_gpu(
    char *storev, magma_int_t *m, magma_int_t *n, magma_int_t *k, magma_int_t *ib,
    magma_int_t *ipiv,
    devptr_t *dL1, magma_int_t *lddl1,
    devptr_t *dL, magma_int_t *lddl,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_zgessm_gpu(
        *storev, *m, *n, *k, *ib,
        ipiv,
        magma_zdevptr(dL1), *lddl1,
        magma_zdevptr(dL), *lddl,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_zgesv_gpu MAGMA_GPU_FORTRAN_NAME( zgesv, ZGESV )
void magmaf_zgesv_gpu(
    magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *ipiv,
    devptr_t *dB, magma_int_t *lddb,
    magma_int_t *info )
{
    magma_zgesv_gpu(
        *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        ipiv,
        magma_zdevptr(dB), *lddb,
        info );
}

#define magmaf_zgetf2_gpu MAGMA_GPU_FORTRAN_NAME( zgetf2, ZGETF2 )
void magmaf_zgetf2_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *lda,
    magma_int_t *ipiv,
    magma_int_t*info )
{
    magma_zgetf2_gpu(
        *m, *n,
        magma_zdevptr(dA), *lda,
        ipiv,
        info );
}

#define magmaf_zgetrf_gpu MAGMA_GPU_FORTRAN_NAME( zgetrf, ZGETRF )
void magmaf_zgetrf_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *ipiv,
    magma_int_t *info )
{
    magma_zgetrf_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        ipiv,
        info );
}

#define magmaf_zgetrf_m MAGMA_FORTRAN_NAME( zgetrf_m, ZGETRF_M )
void magmaf_zgetrf_m(
    magma_int_t *num_gpus0, magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *a, magma_int_t *lda,
    magma_int_t *ipiv,
    magma_int_t *info )
{
    magma_zgetrf_m(
        *num_gpus0, *m, *n,
        a, *lda,
        ipiv,
        info );
}

#define magmaf_zgetrf_piv MAGMA_FORTRAN_NAME( zgetrf_piv, ZGETRF_PIV )
void magmaf_zgetrf_piv(
    magma_int_t *m, magma_int_t *n, magma_int_t *NB,
    magmaDoubleComplex *a, magma_int_t *lda,
    magma_int_t *ipiv,
    magma_int_t *info )
{
    magma_zgetrf_piv(
        *m, *n, *NB,
        a, *lda,
        ipiv,
        info );
}

#define magmaf_zgetrf_nopiv_gpu MAGMA_GPU_FORTRAN_NAME( zgetrf_nopiv, ZGETRF_NOPIV )
void magmaf_zgetrf_nopiv_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_zgetrf_nopiv_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_zgetri_gpu MAGMA_GPU_FORTRAN_NAME( zgetri, ZGETRI )
void magmaf_zgetri_gpu(
    magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *ipiv,
    devptr_t *dwork, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgetri_gpu(
        *n,
        magma_zdevptr(dA), *ldda,
        ipiv,
        magma_zdevptr(dwork), *lwork,
        info );
}

#define magmaf_zgetrs_gpu MAGMA_GPU_FORTRAN_NAME( zgetrs, ZGETRS )
void magmaf_zgetrs_gpu(
    char *trans, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *ipiv,
    devptr_t *dB, magma_int_t *lddb,
    magma_int_t *info )
{
    magma_zgetrs_gpu(
        *trans, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        ipiv,
        magma_zdevptr(dB), *lddb,
        info );
}

#define magmaf_zlaqps2_gpu MAGMA_GPU_FORTRAN_NAME( zlaqps2, ZLAQPS2 )
void magmaf_zlaqps2_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *offset, magma_int_t *nb,
    magma_int_t *kb,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    double *vn1,
    double *vn2,
    magmaDoubleComplex *auxv,
    devptr_t *dF, magma_int_t *lddf )
{
    magma_zlaqps2_gpu(
        *m, *n, *offset, *nb,
        kb,
        A, *lda,
        jpvt,
        tau,
        vn1,
        vn2,
        auxv,
        magma_zdevptr(dF), *lddf );
}

#define magmaf_zlaqps3_gpu MAGMA_GPU_FORTRAN_NAME( zlaqps3, ZLAQPS3 )
void magmaf_zlaqps3_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *offset, magma_int_t *nb,
    magma_int_t *kb,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    double *vn1,
    double *vn2,
    magmaDoubleComplex *auxv,
    devptr_t *dF, magma_int_t *lddf )
{
    magma_zlaqps3_gpu(
        *m, *n, *offset, *nb,
        kb,
        A, *lda,
        jpvt,
        tau,
        vn1,
        vn2,
        auxv,
        magma_zdevptr(dF), *lddf );
}

#define magmaf_zlarf_gpu MAGMA_GPU_FORTRAN_NAME( zlarf, ZLARF )
void magmaf_zlarf_gpu(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *v,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *c, magma_int_t *ldc,
    double *xnorm )
{
    magma_zlarf_gpu(
        *m, *n,
        v,
        tau,
        c, *ldc,
        xnorm );
}

#define magmaf_zlarfb_gpu MAGMA_GPU_FORTRAN_NAME( zlarfb, ZLARFB )
void magmaf_zlarfb_gpu(
    char *side, char *trans, char *direct, char *storev, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *dv, magma_int_t *ldv,
    devptr_t *dt, magma_int_t *ldt,
    devptr_t *dc, magma_int_t *ldc,
    devptr_t *dwork, magma_int_t *ldwork )
{
    magma_zlarfb_gpu(
        *side, *trans, *direct, *storev, *m, *n, *k,
        magma_zdevptr(dv), *ldv,
        magma_zdevptr(dt), *ldt,
        magma_zdevptr(dc), *ldc,
        magma_zdevptr(dwork), *ldwork );
}

#define magmaf_zlarfb2_gpu MAGMA_GPU_FORTRAN_NAME( zlarfb2, ZLARFB2 )
void magmaf_zlarfb2_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *dV, magma_int_t *ldv,
    devptr_t *dT, magma_int_t *ldt,
    devptr_t *dC, magma_int_t *ldc,
    devptr_t *dwork, magma_int_t *ldwork )
{
    magma_zlarfb2_gpu(
        *m, *n, *k,
        magma_zdevptr(dV), *ldv,
        magma_zdevptr(dT), *ldt,
        magma_zdevptr(dC), *ldc,
        magma_zdevptr(dwork), *ldwork );
}

#define magmaf_zlarfb_gpu_gemm MAGMA_FORTRAN_NAME( zlarfb_gpu_gemm, ZLARFB_GPU_GEMM )
void magmaf_zlarfb_gpu_gemm(
    char *side, char *trans, char *direct, char *storev, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    const magmaDoubleComplex *dv, magma_int_t *ldv,
    const magmaDoubleComplex *dt, magma_int_t *ldt,
    magmaDoubleComplex *dc, magma_int_t *ldc,
    magmaDoubleComplex *dwork, magma_int_t *ldwork,
    magmaDoubleComplex *dworkvt, magma_int_t *ldworkvt )
{
    magma_zlarfb_gpu_gemm(
        *side, *trans, *direct, *storev, *m, *n, *k,
        dv, *ldv,
        dt, *ldt,
        dc, *ldc,
        dwork, *ldwork,
        dworkvt, *ldworkvt );
}

#define magmaf_zposv_gpu MAGMA_GPU_FORTRAN_NAME( zposv, ZPOSV )
void magmaf_zposv_gpu(
    char *uplo, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    devptr_t *dB, magma_int_t *lddb,
    magma_int_t *info )
{
    magma_zposv_gpu(
        *uplo, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        magma_zdevptr(dB), *lddb,
        info );
}

#define magmaf_zpotf2_gpu MAGMA_GPU_FORTRAN_NAME( zpotf2, ZPOTF2 )
void magmaf_zpotf2_gpu(
    magma_uplo_t *uplo, magma_int_t *n,
    devptr_t *dA, magma_int_t *lda,
    magma_int_t *info )
{
    magma_zpotf2_gpu(
        *uplo, *n,
        magma_zdevptr(dA), *lda,
        info );
}

#define magmaf_zpotrf_gpu MAGMA_GPU_FORTRAN_NAME( zpotrf, ZPOTRF )
void magmaf_zpotrf_gpu(
    char *uplo, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_zpotrf_gpu(
        *uplo, *n,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_zpotri_gpu MAGMA_GPU_FORTRAN_NAME( zpotri, ZPOTRI )
void magmaf_zpotri_gpu(
    char *uplo, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_zpotri_gpu(
        *uplo, *n,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_zlauum_gpu MAGMA_GPU_FORTRAN_NAME( zlauum, ZLAUUM )
void magmaf_zlauum_gpu(
    char *uplo, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_zlauum_gpu(
        *uplo, *n,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_ztrtri_gpu MAGMA_GPU_FORTRAN_NAME( ztrtri, ZTRTRI )
void magmaf_ztrtri_gpu(
    char *uplo, char *diag, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda,
    magma_int_t *info )
{
    magma_ztrtri_gpu(
        *uplo, *diag, *n,
        magma_zdevptr(dA), *ldda,
        info );
}

#define magmaf_zhetrd_gpu MAGMA_GPU_FORTRAN_NAME( zhetrd, ZHETRD )
void magmaf_zhetrd_gpu(
    char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    double *d,
    double *e,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zhetrd_gpu(
        *uplo, *n,
        magma_zdevptr(da), *ldda,
        d,
        e,
        tau,
        wa, *ldwa,
        work, *lwork,
        info );
}

#define magmaf_zhetrd2_gpu MAGMA_GPU_FORTRAN_NAME( zhetrd2, ZHETRD2 )
void magmaf_zhetrd2_gpu(
    char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    double *d,
    double *e,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    devptr_t *dwork, magma_int_t *ldwork,
    magma_int_t *info )
{
    magma_zhetrd2_gpu(
        *uplo, *n,
        magma_zdevptr(da), *ldda,
        d,
        e,
        tau,
        wa, *ldwa,
        work, *lwork,
        magma_zdevptr(dwork), *ldwork,
        info );
}

#define magmaf_zhetrd_hb2st MAGMA_FORTRAN_NAME( zhetrd_hb2st, ZHETRD_HB2ST )
void magmaf_zhetrd_hb2st(
    magma_int_t *threads, char *uplo, magma_int_t *n, magma_int_t *nb, magma_int_t *Vblksiz,
    magmaDoubleComplex *A, magma_int_t *lda,
    double *D,
    double *E,
    magmaDoubleComplex *V, magma_int_t *ldv,
    magmaDoubleComplex *TAU, magma_int_t *compT,
    magmaDoubleComplex *T, magma_int_t *ldt )
{
    magma_zhetrd_hb2st(
        *threads, *uplo, *n, *nb, *Vblksiz,
        A, *lda,
        D,
        E,
        V, *ldv,
        TAU, *compT,
        T, *ldt );
}

#define magmaf_zhetrd_he2hb MAGMA_FORTRAN_NAME( zhetrd_he2hb, ZHETRD_HE2HB )
void magmaf_zhetrd_he2hb(
    char *uplo, magma_int_t *n, magma_int_t *NB,
    magmaDoubleComplex *a, magma_int_t *lda,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    devptr_t *dT, magma_int_t *threads,
    magma_int_t *info )
{
    magma_zhetrd_he2hb(
        *uplo, *n, *NB,
        a, *lda,
        tau,
        work, *lwork,
        magma_zdevptr(dT), *threads,
        info );
}

#define magmaf_zpotrs_gpu MAGMA_GPU_FORTRAN_NAME( zpotrs, ZPOTRS )
void magmaf_zpotrs_gpu(
    char *uplo, magma_int_t *n, magma_int_t *nrhs,
    devptr_t *dA, magma_int_t *ldda,
    devptr_t *dB, magma_int_t *lddb,
    magma_int_t *info )
{
    magma_zpotrs_gpu(
        *uplo, *n, *nrhs,
        magma_zdevptr(dA), *ldda,
        magma_zdevptr(dB), *lddb,
        info );
}

#define magmaf_zssssm_gpu MAGMA_GPU_FORTRAN_NAME( zssssm, ZSSSSM )
void magmaf_zssssm_gpu(
    char *storev, magma_int_t *m1, magma_int_t *n1, magma_int_t *m2, magma_int_t *n2, magma_int_t *k, magma_int_t *ib,
    devptr_t *dA1, magma_int_t *ldda1,
    devptr_t *dA2, magma_int_t *ldda2,
    devptr_t *dL1, magma_int_t *lddl1,
    devptr_t *dL2, magma_int_t *lddl2,
    magma_int_t *IPIV,
    magma_int_t *info )
{
    magma_zssssm_gpu(
        *storev, *m1, *n1, *m2, *n2, *k, *ib,
        magma_zdevptr(dA1), *ldda1,
        magma_zdevptr(dA2), *ldda2,
        magma_zdevptr(dL1), *lddl1,
        magma_zdevptr(dL2), *lddl2,
        IPIV,
        info );
}

#define magmaf_zungqr_gpu MAGMA_GPU_FORTRAN_NAME( zungqr, ZUNGQR )
void magmaf_zungqr_gpu(
    magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *da, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dwork, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zungqr_gpu(
        *m, *n, *k,
        magma_zdevptr(da), *ldda,
        tau,
        magma_zdevptr(dwork), *nb,
        info );
}

#define magmaf_zunmql2_gpu MAGMA_GPU_FORTRAN_NAME( zunmql2, ZUNMQL2 )
void magmaf_zunmql2_gpu(
    char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *da, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dc, magma_int_t *lddc,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magma_int_t *info )
{
    magma_zunmql2_gpu(
        *side, *trans, *m, *n, *k,
        magma_zdevptr(da), *ldda,
        tau,
        magma_zdevptr(dc), *lddc,
        wa, *ldwa,
        info );
}

#define magmaf_zunmqr_gpu MAGMA_GPU_FORTRAN_NAME( zunmqr, ZUNMQR )
void magmaf_zunmqr_gpu(
    char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *dA, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dC, magma_int_t *lddc,
    magmaDoubleComplex *hwork, magma_int_t *lwork,
    devptr_t *dT, magma_int_t *nb,
    magma_int_t *info )
{
    magma_zunmqr_gpu(
        *side, *trans, *m, *n, *k,
        magma_zdevptr(dA), *ldda,
        tau,
        magma_zdevptr(dC), *lddc,
        hwork, *lwork,
        magma_zdevptr(dT), *nb,
        info );
}

#define magmaf_zunmqr2_gpu MAGMA_GPU_FORTRAN_NAME( zunmqr2, ZUNMQR2 )
void magmaf_zunmqr2_gpu(
    char *side, char *trans, magma_int_t *m, magma_int_t *n, magma_int_t *k,
    devptr_t *da, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dc, magma_int_t *lddc,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magma_int_t *info )
{
    magma_zunmqr2_gpu(
        *side, *trans, *m, *n, *k,
        magma_zdevptr(da), *ldda,
        tau,
        magma_zdevptr(dc), *lddc,
        wa, *ldwa,
        info );
}

#define magmaf_zunmtr_gpu MAGMA_GPU_FORTRAN_NAME( zunmtr, ZUNMTR )
void magmaf_zunmtr_gpu(
    char *side, char *uplo, char *trans, magma_int_t *m, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    magmaDoubleComplex *tau,
    devptr_t *dc, magma_int_t *lddc,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magma_int_t *info )
{
    magma_zunmtr_gpu(
        *side, *uplo, *trans, *m, *n,
        magma_zdevptr(da), *ldda,
        tau,
        magma_zdevptr(dc), *lddc,
        wa, *ldwa,
        info );
}

#if defined(PRECISION_z) || defined(PRECISION_c)
#define magmaf_zgeqp3_gpu MAGMA_GPU_FORTRAN_NAME( zgeqp3, ZGEQP3 )
void magmaf_zgeqp3_gpu(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *info )
{
    magma_zgeqp3_gpu(
        *m, *n,
        A, *lda,
        jpvt,
        tau,
        work, *lwork,
        rwork,
        info );
}

#define magmaf_zheevd_gpu MAGMA_GPU_FORTRAN_NAME( zheevd, ZHEEVD )
void magmaf_zheevd_gpu(
    char *jobz, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    double *w,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd_gpu(
        *jobz, *uplo, *n,
        magma_zdevptr(da), *ldda,
        w,
        wa, *ldwa,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_gpu MAGMA_GPU_FORTRAN_NAME( zheevdx, ZHEEVDX )
void magmaf_zheevdx_gpu(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_gpu(
        *jobz, *range, *uplo, *n,
        magma_zdevptr(da), *ldda, *vl, *vu, *il, *iu,
        m,
        w,
        wa, *ldwa,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevx_gpu MAGMA_GPU_FORTRAN_NAME( zheevx, ZHEEVX )
void magmaf_zheevx_gpu(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    devptr_t *dz, magma_int_t *lddz,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *wz, magma_int_t *ldwz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork,
    magma_int_t *iwork,
    magma_int_t *ifail,
    magma_int_t *info )
{
    magma_zheevx_gpu(
        *jobz, *range, *uplo, *n,
        magma_zdevptr(da), *ldda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        magma_zdevptr(dz), *lddz,
        wa, *ldwa,
        wz, *ldwz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magmaf_zheevr_gpu MAGMA_GPU_FORTRAN_NAME( zheevr, ZHEEVR )
void magmaf_zheevr_gpu(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu, double *abstol,
    magma_int_t *m,
    double *w,
    devptr_t *dz, magma_int_t *lddz,
    magma_int_t *isuppz,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *wz, magma_int_t *ldwz,
    magmaDoubleComplex *work, magma_int_t *lwork,
    double *rwork, magma_int_t *lrwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevr_gpu(
        *jobz, *range, *uplo, *n,
        magma_zdevptr(da), *ldda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        magma_zdevptr(dz), *lddz,
        isuppz,
        wa, *ldwa,
        wz, *ldwz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#else
#define magmaf_zgeqp3_gpu MAGMA_GPU_FORTRAN_NAME( zgeqp3, ZGEQP3 )
void magmaf_zgeqp3_gpu(
    magma_int_t *m, magma_int_t *n,
    magmaDoubleComplex *A, magma_int_t *lda,
    magma_int_t *jpvt,
    magmaDoubleComplex *tau,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *info )
{
    magma_zgeqp3_gpu(
        *m, *n,
        A, *lda,
        jpvt,
        tau,
        work, *lwork,
        info );
}

#define magmaf_zheevd_gpu MAGMA_GPU_FORTRAN_NAME( zheevd, ZHEEVD )
void magmaf_zheevd_gpu(
    char *jobz, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    magmaDoubleComplex *w,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevd_gpu(
        *jobz, *uplo, *n,
        magma_zdevptr(da), *ldda,
        w,
        wa, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magmaf_zheevdx_gpu MAGMA_GPU_FORTRAN_NAME( zheevdx, ZHEEVDX )
void magmaf_zheevdx_gpu(
    char *jobz, char *range, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda, double *vl, double *vu, magma_int_t *il, magma_int_t *iu,
    magma_int_t *m,
    double *w,
    magmaDoubleComplex *wa, magma_int_t *ldwa,
    magmaDoubleComplex *work, magma_int_t *lwork,
    magma_int_t *iwork, magma_int_t *liwork,
    magma_int_t *info )
{
    magma_zheevdx_gpu(
        *jobz, *range, *uplo, *n,
        magma_zdevptr(da), *ldda, *vl, *vu, *il, *iu,
        m,
        w,
        wa, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#endif

#define magmaf_zhegst_gpu MAGMA_GPU_FORTRAN_NAME( zhegst, ZHEGST )
void magmaf_zhegst_gpu(
    magma_int_t *itype, char *uplo, magma_int_t *n,
    devptr_t *da, magma_int_t *ldda,
    devptr_t *db, magma_int_t *lddb,
    magma_int_t *info )
{
    magma_zhegst_gpu(
        *itype, *uplo, *n,
        magma_zdevptr(da), *ldda,
        magma_zdevptr(db), *lddb,
        info );
}

/* ////////////////////////////////////////////////////////////////////////////
 -- MAGMA utility function definitions
*/

#define magmaf_zprint MAGMA_FORTRAN_NAME( zprint, ZPRINT )
void magmaf_zprint(
    magma_int_t *m, magma_int_t *n,
    const magmaDoubleComplex  *A, magma_int_t *lda )
{
    magma_zprint(
        *m, *n,
        A, *lda );
}

#define magmaf_zprint_gpu MAGMA_GPU_FORTRAN_NAME( zprint, ZPRINT )
void magmaf_zprint_gpu(
    magma_int_t *m, magma_int_t *n,
    devptr_t *dA, magma_int_t *ldda )
{
    magma_zprint_gpu(
        *m, *n,
        magma_zdevptr(dA), *ldda );
}


#ifdef __cplusplus
}
#endif
