# Substitutions are applied in the order listed. This is important in cases
# where multiple substitutions could match, or when one substitution matches
# the result of a previous substitution. For example, these rules are correct
# in this order:
#
#    ('real',   'double precision',  'real',   'double precision' ),  # before double
#    ('float',  'double',            'float',  'double'           ),
#
# but if switched would translate 'double precision' -> 'float precision',
# which is wrong.
#
# Reorganized 5/2012 Mark Gates

# Dictionary is keyed on substitution type (mixed, normal, etc.)
subs = {
  # ------------------------------------------------------------
  # replacements applied to ALL files.
  'all' : [
    [None, None]
  ],
  
  # ------------------------------------------------------------
  # replacements applied to mixed precision files.
  'mixed' : [
    # ----- Special line indicating column types
    ['ds',                        'zc'                      ],
    
    # ----- Mixed precisions
    ('DS',                        'ZC'                      ),
    ('ds',                        'zc'                      ),
    
    # ----- Preprocessor
    ('#define PRECISION_d',       '#define PRECISION_z'     ),
    ('#define PRECISION_s',       '#define PRECISION_c'     ),
    ('#undef PRECISION_d',        '#undef PRECISION_z'      ),
    ('#undef PRECISION_s',        '#undef PRECISION_c'      ),
    
    # ----- Data types
    ('double',                    'double2'                 ),
    ('float',                     'float2'                  ),
    ('double',                    'cuDoubleComplex'         ),
    ('float',                     'cuFloatComplex'          ),
    ('DOUBLE PRECISION',          'COMPLEX_16'              ),
    ('SINGLE PRECISION',          'COMPLEX'                 ),
    ('real',                      'complex'                 ),
    
    # ----- CBLAS
    ('',                          'CBLAS_SADDR'             ),
    
    # ----- Prefixes
    ('blasf77_d',                 'blasf77_z'               ),
    ('blasf77_s',                 'blasf77_c'               ),
    ('cublasIdamax',              'cublasIzamax'            ),
    ('cublasD',                   'cublasZ'                 ),
    ('cublasS',                   'cublasC'                 ),
    ('lapackf77_d',               'lapackf77_z'             ),
    ('lapackf77_s',               'lapackf77_c'             ),
    ('MAGMA_D',                   'MAGMA_Z'                 ),
    ('MAGMA_S',                   'MAGMA_C'                 ),
    ('magmablas_d',               'magmablas_z'             ),
    ('magmablas_s',               'magmablas_c'             ),
    ('magma_d',                   'magma_z'                 ),
    ('magma_s',                   'magma_c'                 ),
    ('magma_get_d',               'magma_get_z'             ),
    ('magma_get_s',               'magma_get_c'             ),
    
    # ----- Complex numbers
    ('(double)',                  'cuComplexFloatToDouble'  ),
    ('(float)',                   'cuComplexDoubleToFloat'  ),
    ('',                          'cuCrealf'                ),
    ('',                          'cuCimagf'                ),
    ('',                          'cuCreal'                 ),
    ('',                          'cuCimag'                 ),
    ('',                          'cuConj'                  ),
    ('abs',                       'cuCabs'                  ),  
    ('absf',                      'cuCabsf'                 ),
    
    # ----- PLASMA / MAGMA
    ('magma_sdgetrs',             'magma_czgetrs'           ),
    
    # ----- Constants
    ('CblasTrans',                'CblasConjTrans'          ),
    ('MagmaTrans',                'MagmaConjTrans'          ),
    
    # ----- BLAS and LAPACK, lowercase, alphabetic order
    # copy & paste these to uppercase below and fix case.
    # mixed precision
    ('dsaxpy',                    'zcaxpy'                  ),
    ('dslaswp',                   'zclaswp'                 ),
    
    # regular
    ('daxpy',                     'zaxpy'                   ),
    ('dgemm',                     'zgemm'                   ),
    ('dgesv',                     'zgesv'                   ),
    ('dlacpy',                    'zlacpy'                  ),
    ('dlange',                    'zlange'                  ),
    ('dlansy',                    'zlansy'                  ),
    ('dlarnv',                    'zlarnv'                  ),
    ('dpotrf',                    'zpotrf'                  ),
    ('dtrmm',                     'ztrmm'                   ),
    ('dtrsm',                     'ztrsm'                   ),
    ('dtrsv',                     'ztrsv'                   ),
    ('idamax',                    'izamax'                  ),
    ('spotrf',                    'cpotrf'                  ),
    ('strmm',                     'ctrmm'                   ),
    ('strsm',                     'ctrsm'                   ),
    ('strsv',                     'ctrsv'                   ),
    
    # ----- BLAS and LAPACK, where complex base name != real base name
    # with precision
    ('dlag2s',                    'zlag2c'                  ),
    ('dlagsy',                    'zlaghe'                  ),
    ('dlansy',                    'zlanhe'                  ),
    ('dlat2s',                    'zlat2c'                  ),
    ('dormqr',                    'zunmqr'                  ),
    ('dsymm',                     'zhemm'                   ),
    ('dsymv',                     'zhemv'                   ),
    ('dsyrk',                     'zherk'                   ),
    ('slag2d',                    'clag2z'                  ),
    ('slansy',                    'clanhe'                  ),
    ('slat2d',                    'clat2z'                  ),
    
    # without precision
    ('lag2s',                     'lag2c'                   ),
    ('lagsy',                     'laghe'                   ),
    ('lansy',                     'lanhe'                   ),
    ('lat2s',                     'lat2c'                   ),
    ('ormqr',                     'unmqr'                   ),
    ('symm',                      'hemm'                    ),
    ('symv',                      'hemv'                    ),
    ('syrk',                      'herk'                    ),
    ('lag2d',                     'lag2z'                   ),
    ('lansy',                     'lanhe'                   ),
    ('lat2d',                     'lat2z'                   ),
    
    # ----- BLAS AND LAPACK, UPPERCASE, ALPHABETIC ORDER
    # COPY & PASTE THESE TO UPPERCASE BELOW AND FIX CASE.
    # MIXED PRECISION
    ('DSAXPY',                    'ZCAXPY'                  ),
    ('DSLASWP',                   'ZCLASWP'                 ),
    
    # REGULAR
    ('DAXPY',                     'ZAXPY'                   ),
    ('DGEMM',                     'ZGEMM'                   ),
    ('DGESV',                     'ZGESV'                   ),
    ('DLACPY',                    'ZLACPY'                  ),
    ('DLANGE',                    'ZLANGE'                  ),
    ('DLANSY',                    'ZLANSY'                  ),
    ('DLARNV',                    'ZLARNV'                  ),
    ('DPOTRF',                    'ZPOTRF'                  ),
    ('DTRMM',                     'ZTRMM'                   ),
    ('DTRSM',                     'ZTRSM'                   ),
    ('DTRSV',                     'ZTRSV'                   ),
    ('IDAMAX',                    'IZAMAX'                  ),
    ('SPOTRF',                    'CPOTRF'                  ),
    ('STRMM',                     'CTRMM'                   ),
    ('STRSM',                     'CTRSM'                   ),
    ('STRSV',                     'CTRSV'                   ),
    
    # ----- BLAS AND LAPACK, WHERE COMPLEX BASE NAME != REAL BASE NAME
    # WITH PRECISION
    ('DLAG2S',                    'ZLAG2C'                  ),
    ('DLAGSY',                    'ZLAGHE'                  ),
    ('DLANSY',                    'ZLANHE'                  ),
    ('DLAT2S',                    'ZLAT2C'                  ),
    ('DORMQR',                    'ZUNMQR'                  ),
    ('DSYMM',                     'ZHEMM'                   ),
    ('DSYMV',                     'ZHEMV'                   ),
    ('DSYRK',                     'ZHERK'                   ),
    ('SLAG2D',                    'CLAG2Z'                  ),
    ('SLANSY',                    'CLANHE'                  ),
    ('SLAT2D',                    'CLAT2Z'                  ),
    
    # WITHOUT PRECISION
    ('LAG2S',                     'LAG2C'                   ),
    ('LAGSY',                     'LAGHE'                   ),
    ('LANSY',                     'LANHE'                   ),
    ('LAT2S',                     'LAT2C'                   ),
    ('ORMQR',                     'UNMQR'                   ),
    ('SYMM',                      'HEMM'                    ),
    ('SYMV',                      'HEMV'                    ),
    ('SYRK',                      'HERK'                    ),
    ('LAG2D',                     'LAG2Z'                   ),
    ('LANSY',                     'LANHE'                   ),
    ('LAT2D',                     'LAT2Z'                   ),
  ],
  
  # ------------------------------------------------------------
  # replacements applied to most files.
  'normal' : [
    # ----- Special line indicating column types
    # old python (2.4) requires this line to be list [] rather than tuple () to use index() function.
    ['s',              'd',              'c',              'z'               ],
    
    # ----- Preprocessor
    ('#define PRECISION_s', '#define PRECISION_d', '#define PRECISION_c', '#define PRECISION_z' ),
    ('#undef PRECISION_s',  '#undef PRECISION_d',  '#undef PRECISION_c',  '#undef PRECISION_z'  ),
    ('#define REAL',        '#define REAL',        '#define COMPLEX',     '#define COMPLEX'     ),
    ('#undef COMPLEX',      '#undef COMPLEX',      '#undef REAL',         '#undef REAL'         ),
    ('#define SINGLE',      '#define DOUBLE',      '#define SINGLE',      '#define DOUBLE'      ),
    ('#undef DOUBLE',       '#undef SINGLE',       '#undef DOUBLE',       '#undef SINGLE'       ),
    
    # ----- Data types
    ('real',                'double precision',    'real',                'double precision'    ),  # before double
    ('float',               'double',              'float',               'double'              ),
    ('float',               'double',              'cuFloatComplex',      'cuDoubleComplex'     ),
    ('float',               'double',              'PLASMA_Complex32_t',  'PLASMA_Complex64_t'  ),
    ('real',                'double precision',    'complex',             'complex\*16'         ),
    ('REAL',                'DOUBLE_PRECISION',    'COMPLEX',             'COMPLEX_16'          ),
    ('sizeof_real',         'sizeof_double',       'sizeof_complex',      'sizeof_complex_16'   ),  # before complex
    ('real',                'real',                'complex',             'complex'             ),
    ('float',               'double',              'float2',              'double2'             ),
    
    # ----- Text
    ('symmetric',      'symmetric',      'Hermitian',      'Hermitian'       ),
    ('\*\*T',          '\*\*T',          '\*\*H',          '\*\*H'           ),
    ('%f',             '%lf',            '%f',             '%lf'             ),  # for scanf
    
    # ----- CBLAS
    ('cblas_sasum',    'cblas_dasum',    'cblas_scasum',   'cblas_dzasum'    ),
    ('cblas_snrm2',    'cblas_dnrm2',    'cblas_scnrm2',   'cblas_dznrm2'    ),
    ('',               '',               'CBLAS_SADDR',    'CBLAS_SADDR'     ),
    
    # ----- Core BLAS
    ('CORE_sasum',     'CORE_dasum',     'CORE_scasum',    'CORE_dzasum'     ),
    ('core_sasum',     'core_dasum',     'core_scasum',    'core_dzasum'     ),
    
    # ----- Prefixes
    # Changing prefixes first requires some calls to be fixed without precision,
    # e.g., her2k -> syr2k instead of zher2k -> ssyr2k.
    # See BLAS and LAPACK without precision, below.
    ('blasf77_s',      'blasf77_d',      'blasf77_c',      'blasf77_z'       ),
    ('blasf77_s',      'blasf77_d',      'blasf77_s',      'blasf77_d'       ),
    ('BLAS_S',         'BLAS_D',         'BLAS_C',         'BLAS_Z'          ),
    ('BLAS_s',         'BLAS_d',         'BLAS_c',         'BLAS_z'          ),
    ('BLAS_s',         'BLAS_d',         'BLAS_s',         'BLAS_d'          ),
    ('blas_is',        'blas_id',        'blas_ic',        'blas_iz'         ),
    ('blas_s',         'blas_d',         'blas_c',         'blas_z'          ),
    ('compute_s',      'compute_d',      'compute_c',      'compute_z'       ),
    ('control_s',      'control_d',      'control_c',      'control_z'       ),
    ('CORE_S',         'CORE_D',         'CORE_C',         'CORE_Z'          ),
    ('CORE_s',         'CORE_d',         'CORE_c',         'CORE_z'          ),
    ('core_s',         'core_d',         'core_c',         'core_z'          ),
    ('CORE_s',         'CORE_d',         'CORE_s',         'CORE_d'          ),
    ('cublasS',        'cublasD',        'cublasC',        'cublasZ'         ),
    ('example_s',      'example_d',      'example_c',      'example_z'       ),
    ('lapackf77_s',    'lapackf77_d',    'lapackf77_c',    'lapackf77_z'     ),
    ('lapackf77_s',    'lapackf77_d',    'lapackf77_s',    'lapackf77_d'     ),
    ('MAGMABLAS_S',    'MAGMABLAS_D',    'MAGMABLAS_C',    'MAGMABLAS_Z'     ),
    ('magmablas_s',    'magmablas_d',    'magmablas_c',    'magmablas_z'     ),
    ('magmaf_s',       'magmaf_d',       'magmaf_c',       'magmaf_z'        ),
    ('magma_get_s',    'magma_get_d',    'magma_get_c',    'magma_get_z'     ),
    ('MAGMA_S',        'MAGMA_D',        'MAGMA_C',        'MAGMA_Z'         ),
    ('magma_s',        'magma_d',        'magma_c',        'magma_z'         ),
    ('SCHED_s',        'SCHED_d',        'SCHED_c',        'SCHED_z'         ),
    ('testing_ds',     'testing_ds',     'testing_zc',     'testing_zc'      ),
    ('TESTING_S',      'TESTING_D',      'TESTING_C',      'TESTING_Z'       ),
    ('testing_s',      'testing_d',      'testing_c',      'testing_z'       ),
    ('Workspace_s',    'Workspace_d',    'Workspace_c',    'Workspace_z'     ),
    ('workspace_s',    'workspace_d',    'workspace_c',    'workspace_z'     ),
    ('QUARK_Insert_Task_s', 'QUARK_Insert_Task_d', 'QUARK_Insert_Task_c', 'QUARK_Insert_Task_z' ),
    
    # ----- Complex numbers
    # \b regexp here avoids conjugate -> conjfugate,
    # assuming we always translate from z, not to z.
    ('',               '',               'conjf',          'conj\b'          ),
    ('fabsf',          'fabs',           'cabsf',          'cabs'            ),
    ('',               '',               'cuCrealf',       'cuCreal'         ),
    ('',               '',               'cuCimagf',       'cuCimag'         ),
    ('',               '',               'cuConjf',        'cuConj'          ),
    ('fabsf',          'fabs',           'cuCabsf',        'cuCabs'          ),
    
    # ----- CUDA
    ('cublasIsamax',   'cublasIdamax',   'cublasIcamax',   'cublasIzamax'    ),
    ('cublasIsamax',   'cublasIdamax',   'cublasIsamax',   'cublasIdamax'    ),
    ('cublasSnrm2',    'cublasDnrm2',    'cublasScnrm2',   'cublasDznrm2'    ),
    
    # ----- PLASMA / MAGMA
    ('bsy2trc',        'bsy2trc',        'bhe2trc',        'bhe2trc'         ),
    ('cpu_gpu_s',      'cpu_gpu_d',      'cpu_gpu_c',      'cpu_gpu_z'       ),
    ('magma_ssqrt',    'magma_dsqrt',    'magma_ssqrt',    'magma_dsqrt'     ),
    ('sauxiliary',     'dauxiliary',     'cauxiliary',     'zauxiliary'      ),
    ('sbcyclic',       'dbcyclic',       'cbcyclic',       'zbcyclic'        ),
    ('sbulge',         'dbulge',         'cbulge',         'zbulge'          ),
    ('sgetmatrix',     'dgetmatrix',     'cgetmatrix',     'zgetmatrix'      ),
    ('sinplace',       'dinplace',       'cinplace',       'zinplace'        ),
    ('smalloc',        'dmalloc',        'cmalloc',        'zmalloc'         ),
    ('smalloc',        'dmalloc',        'smalloc',        'dmalloc'         ),
    ('spanel_to_q',    'dpanel_to_q',    'cpanel_to_q',    'zpanel_to_q'     ),
    ('spermute',       'dpermute',       'cpermute',       'zpermute'        ),
    ('sprint',         'dprint',         'cprint',         'zprint'          ),
    ('sq_to_panel',    'dq_to_panel',    'cq_to_panel',    'zq_to_panel'     ),
    ('sset',           'dset',           'cset',           'zset'            ),
    ('ssetmatrix',     'dsetmatrix',     'csetmatrix',     'zsetmatrix'      ),
    ('SSIZE',          'DSIZE',          'CSIZE',          'ZSIZE'           ),
    ('ssplit',         'dsplit',         'csplit',         'zsplit'          ),
    ('stile',          'dtile',          'ctile',          'ztile'           ),
    ('stranspose',     'dtranspose',     'ctranspose',     'ztranspose'      ),
    ('szero',          'dzero',          'czero',          'zzero'           ),
    
    # ----- Constants
    ('CblasTrans',     'CblasTrans',     'CblasConjTrans', 'CblasConjTrans'  ),
    ('MagmaTrans',     'MagmaTrans',     'MagmaConjTrans', 'MagmaConjTrans'  ),
    
    # ----- BLAS and LAPACK, lowercase, alphabetic order
    # copy & paste these to uppercase below and fix case.
    # used for filenames lacking magma_z, etc. prefix
    ('isamax',         'idamax',         'icamax',         'izamax'          ),
    ('isamax',         'idamax',         'isamax',         'idamax'          ),
    ('saxpy',          'daxpy',          'caxpy',          'zaxpy'           ),
    ('scopy',          'dcopy',          'ccopy',          'zcopy'           ),
    ('sgemv',          'dgemv',          'cgemv',          'zgemv'           ),
    ('sscal',          'dscal',          'cscal',          'zscal'           ),
    ('sscal',          'dscal',          'csscal',         'zdscal'          ),
    ('sscal',          'dscal',          'sscal',          'dscal'           ),  # zdscal -> csscal
    ('sswap',          'dswap',          'cswap',          'zswap'           ),
    ('ssymm',          'dsymm',          'csymm',          'zsymm'           ),
    ('ssymv',          'dsymv',          'csymv',          'zsymv'           ),
    ('ssyr2k',         'dsyr2k',         'csyr2k',         'zsyr2k'          ),
    ('ssyrk',          'dsyrk',          'csyrk',          'zsyrk'           ),
    ('strmm',          'dtrmm',          'ctrmm',          'ztrmm'           ),
    ('strmv',          'dtrmv',          'ctrmv',          'ztrmv'           ),
    ('strsm',          'dtrsm',          'ctrsm',          'ztrsm'           ),
    ('strsv',          'dtrsv',          'ctrsv',          'ztrsv'           ),
    
    # LAPACK
    ('sbdsqr',         'dbdsqr',         'cbdsqr',         'zbdsqr'          ),
    ('sbdt01',         'dbdt01',         'cbdt01',         'zbdt01'          ),
    ('scheck',         'dcheck',         'ccheck',         'zcheck'          ),
    ('sgebak',         'dgebak',         'cgebak',         'zgebak'          ),
    ('sgebal',         'dgebal',         'cgebal',         'zgebal'          ),
    ('sgebd2',         'dgebd2',         'cgebd2',         'zgebd2'          ),
    ('sgebrd',         'dgebrd',         'cgebrd',         'zgebrd'          ),
    ('sgeev',          'dgeev',          'cgeev',          'zgeev'           ),
    ('sgehd2',         'dgehd2',         'cgehd2',         'zgehd2'          ),
    ('sgehrd',         'dgehrd',         'cgehrd',         'zgehrd'          ),
    ('sgelq2',         'dgelq2',         'cgelq2',         'zgelq2'          ),
    ('sgelqf',         'dgelqf',         'cgelqf',         'zgelqf'          ),
    ('sgelqs',         'dgelqs',         'cgelqs',         'zgelqs'          ),
    ('sgels',          'dgels',          'cgels',          'zgels'           ),
    ('sgemm',          'dgemm',          'cgemm',          'zgemm'           ),
    ('sgeqlf',         'dgeqlf',         'cgeqlf',         'zgeqlf'          ),
    ('sgeqp3',         'dgeqp3',         'cgeqp3',         'zgeqp3'          ),
    ('sgeqr2',         'dgeqr2',         'cgeqr2',         'zgeqr2'          ),
    ('sgeqrf',         'dgeqrf',         'cgeqrf',         'zgeqrf'          ),
    ('sgeqrs',         'dgeqrs',         'cgeqrs',         'zgeqrs'          ),
    ('sgessm',         'dgessm',         'cgessm',         'zgessm'          ),
    ('sgesv',          'dgesv',          'cgesv',          'zgesv'           ),
    ('sgesv',          'sgesv',          'cgesv',          'cgesv'           ),
    ('sget22',         'dget22',         'cget22',         'zget22'          ),
    ('sgetf2',         'dgetf2',         'cgetf2',         'zgetf2'          ),
    ('sgetrf',         'dgetrf',         'cgetrf',         'zgetrf'          ),
    ('sgetri',         'dgetri',         'cgetri',         'zgetri'          ),
    ('sgetrl',         'dgetrl',         'cgetrl',         'zgetrl'          ),
    ('sgetrs',         'dgetrs',         'cgetrs',         'zgetrs'          ),
    ('shseqr',         'dhseqr',         'chseqr',         'zhseqr'          ),
    ('shst01',         'dhst01',         'chst01',         'zhst01'          ),
    ('slabad',         'dlabad',         'slabad',         'dlabad'          ),
    ('slabrd',         'dlabrd',         'clabrd',         'zlabrd'          ),
    ('slacgv',         'dlacgv',         'clacgv',         'zlacgv'          ),
    ('slacpy',         'dlacpy',         'clacpy',         'zlacpy'          ),
    ('slaed',          'dlaed',          'slaed',          'dlaed'           ),
    ('slaex',          'dlaex',          'slaex',          'dlaex'           ),
    ('slagsy',         'dlagsy',         'clagsy',         'zlagsy'          ),
    ('slahr',          'dlahr',          'clahr',          'zlahr'           ),
    ('slamc3',         'dlamc3',         'slamc3',         'dlamc3'          ),
    ('slamch',         'dlamch',         'slamch',         'dlamch'          ),
    ('slamrg',         'dlamrg',         'slamrg',         'dlamrg'          ),
    ('slange',         'dlange',         'clange',         'zlange'          ),
    ('slanst',         'dlanst',         'clanst',         'zlanst'          ),
    ('slansy',         'dlansy',         'clansy',         'zlansy'          ),
    ('slantr',         'dlantr',         'clantr',         'zlantr'          ),
    ('slaqps',         'dlaqps',         'claqps',         'zlaqps'          ),
    ('slarfb',         'dlarfb',         'clarfb',         'zlarfb'          ),
    ('slarfg',         'dlarfg',         'clarfg',         'zlarfg'          ),
    ('slarft',         'dlarft',         'clarft',         'zlarft'          ),
    ('slarfx',         'dlarfx',         'clarfx',         'zlarfx'          ),
    ('slarfy',         'dlarfy',         'clarfy',         'zlarfy'          ),
    ('slarnv',         'dlarnv',         'clarnv',         'zlarnv'          ),
    ('slarnv',         'dlarnv',         'slarnv',         'dlarnv'          ),
    ('slartg',         'dlartg',         'clartg',         'zlartg'          ),
    ('slascl',         'dlascl',         'clascl',         'zlascl'          ),
    ('slaset',         'dlaset',         'claset',         'zlaset'          ),
    ('slaswp',         'dlaswp',         'claswp',         'zlaswp'          ),
    ('slatrd',         'dlatrd',         'clatrd',         'zlatrd'          ),
    ('slauum',         'dlauum',         'clauum',         'zlauum'          ),
    ('sposv',          'dposv',          'cposv',          'zposv'           ),
    ('sposv',          'sposv',          'cposv',          'cposv'           ),
    ('spotrf',         'dpotrf',         'cpotrf',         'zpotrf'          ),
    ('spotri',         'dpotri',         'cpotri',         'zpotri'          ),
    ('spotrs',         'dpotrs',         'cpotrs',         'zpotrs'          ),
    ('sqpt01',         'dqpt01',         'cqpt01',         'zqpt01'          ),
    ('sqrt02',         'dqrt02',         'cqrt02',         'zqrt02'          ),
    ('sssssm',         'dssssm',         'cssssm',         'zssssm'          ),
    ('sstebz',         'dstebz',         'sstebz',         'dstebz'          ),
    ('sstedc',         'dstedc',         'cstedc',         'zstedc'          ),
    ('sstedx',         'dstedx',         'cstedx',         'zstedx'          ),
    ('sstedx',         'dstedx',         'sstedx',         'dstedx'          ),
    ('sstein',         'dstein',         'cstein',         'zstein'          ),
    ('sstemr',         'dstemr',         'cstemr',         'zstemr'          ),
    ('ssteqr',         'dsteqr',         'csteqr',         'zsteqr'          ),
    ('ssterf',         'dsterf',         'ssterf',         'dsterf'          ),
    ('ssterm',         'dsterm',         'csterm',         'zsterm'          ),
    ('sstt21',         'dstt21',         'cstt21',         'zstt21'          ),
    ('strevc',         'dtrevc',         'ctrevc',         'ztrevc'          ),
    ('strsmpl',        'dtrsmpl',        'ctrsmpl',        'ztrsmpl'         ),
    ('strtri',         'dtrtri',         'ctrtri',         'ztrtri'          ),
    ('stsqrt',         'dtsqrt',         'ctsqrt',         'ztsqrt'          ),
    ('ststrf',         'dtstrf',         'ctstrf',         'ztstrf'          ),
    ('sungesv',        'sungesv',        'cungesv',        'cungesv'         ),
    ('sstegr',         'dstegr',         'cstegr',         'zstegr'          ),
    
    # ----- BLAS and LAPACK, where complex base name != real base name
    # BLAS, with precision
    ('sdot',           'ddot',           'cdotc',          'zdotc'           ),
    ('sdot_sub',       'ddot_sub',       'cdotc_sub',      'zdotc_sub'       ),
    ('sdot_sub',       'ddot_sub',       'cdotu_sub',      'zdotu_sub'       ),
    ('sger',           'dger',           'cgerc',          'zgerc'           ),
    ('sger',           'dger',           'cgeru',          'zgeru'           ),
    ('snrm2',          'dnrm2',          'scnrm2',         'dznrm2'          ),
    ('ssymm',          'dsymm',          'chemm',          'zhemm'           ),
    ('ssymv',          'dsymv',          'chemv',          'zhemv'           ),
    ('ssyr2',          'dsyr2',          'cher2',          'zher2'           ),
    ('ssyr2k',         'dsyr2k',         'cher2k',         'zher2k'          ),
    ('ssyrk',          'dsyrk',          'cherk',          'zherk'           ),
    
    # LAPACK, with precision
    ('slag2d',         'dlag2s',         'clag2z',         'zlag2c'          ),
    ('slagsy',         'dlagsy',         'claghe',         'zlaghe'          ),
    ('slansy',         'dlansy',         'clanhe',         'zlanhe'          ),
    ('sorg2r',         'dorg2r',         'cung2r',         'zung2r'          ),
    ('sorgbr',         'dorgbr',         'cungbr',         'zungbr'          ),
    ('sorghr',         'dorghr',         'cunghr',         'zunghr'          ),
    ('sorglq',         'dorglq',         'cunglq',         'zunglq'          ),
    ('sorgql',         'dorgql',         'cungql',         'zungql'          ),
    ('sorgqr',         'dorgqr',         'cungqr',         'zungqr'          ),
    ('sorgtr',         'dorgtr',         'cungtr',         'zungtr'          ),
    ('sorm2r',         'dorm2r',         'cunm2r',         'zunm2r'          ),
    ('sormbr',         'dormbr',         'cunmbr',         'zunmbr'          ),
    ('sormlq',         'dormlq',         'cunmlq',         'zunmlq'          ),
    ('sormql',         'dormql',         'cunmql',         'zunmql'          ),
    ('sormqr',         'dormqr',         'cunmqr',         'zunmqr'          ),
    ('sormr2',         'dormr2',         'cunmr2',         'zunmr2'          ),
    ('sormtr',         'dormtr',         'cunmtr',         'zunmtr'          ),
    ('sort01',         'dort01',         'cunt01',         'zunt01'          ),
    ('splgsy',         'dplgsy',         'cplghe',         'zplghe'          ),
    ('ssbtrd',         'dsbtrd',         'chbtrd',         'zhbtrd'          ),
    ('ssybbd',         'dsybbd',         'chebbd',         'zhebbd'          ),
    ('ssyev',          'dsyev',          'cheev',          'zheev'           ),
    ('ssyevd',         'dsyevd',         'cheevd',         'zheevd'          ),
    ('ssygs2',         'dsygs2',         'chegs2',         'zhegs2'          ),
    ('ssygst',         'dsygst',         'chegst',         'zhegst'          ),
    ('ssygvd',         'dsygvd',         'chegvd',         'zhegvd'          ),
    ('ssygvr',         'dsygvr',         'chegvr',         'zhegvr'          ),
    ('ssygvx',         'dsygvx',         'chegvx',         'zhegvx'          ),
    ('ssyt21',         'dsyt21',         'chet21',         'zhet21'          ),
    ('ssytd2',         'dsytd2',         'chetd2',         'zhetd2'          ),
    ('ssytrd',         'dsytrd',         'chetrd',         'zhetrd'          ),
    
    # BLAS, without precision
    # must be after BLAS with precision
    # Ex: cublasZhemm -> cublasShemm -> cublasSsymm
    ('dot',            'dot',            'dotc',           'dotc'            ),
    ('dot_sub',        'dot_sub',        'dotc_sub',       'dotc_sub'        ),
    ('dot_sub',        'dot_sub',        'dotu_sub',       'dotu_sub'        ),
    ('ger',            'ger',            'gerc',           'gerc'            ),
    ('ger',            'ger',            'geru',           'geru'            ),
    ('nrm2',           'nrm2',           'cnrm2',          'znrm2'           ),  # dznrm2 -> dnrm2
    ('symm',           'symm',           'hemm',           'hemm'            ),
    ('symv',           'symv',           'hemv',           'hemv'            ),
    ('syr2',           'syr2',           'her2',           'her2'            ),
    ('syr2k',          'syr2k',          'her2k',          'her2k'           ),
    ('syrk',           'syrk',           'herk',           'herk'            ),
    
    # LAPACK, without precision
    ('lag2d',          'lag2s',          'lag2z',          'lag2c'           ),
    ('lagsy',          'lagsy',          'laghe',          'laghe'           ),
    ('lansy',          'lansy',          'lanhe',          'lanhe'           ),
    ('org2r',          'org2r',          'ung2r',          'ung2r'           ),
    ('orgbr',          'orgbr',          'ungbr',          'ungbr'           ),
    ('orghr',          'orghr',          'unghr',          'unghr'           ),
    ('orglq',          'orglq',          'unglq',          'unglq'           ),
    ('orgql',          'orgql',          'ungql',          'ungql'           ),
    ('orgqr',          'orgqr',          'ungqr',          'ungqr'           ),
    ('orgtr',          'orgtr',          'ungtr',          'ungtr'           ),
    ('orm2r',          'orm2r',          'unm2r',          'unm2r'           ),
    ('ormbr',          'ormbr',          'unmbr',          'unmbr'           ),
    ('ormlq',          'ormlq',          'unmlq',          'unmlq'           ),
    ('ormql',          'ormql',          'unmql',          'unmql'           ),
    ('ormqr',          'ormqr',          'unmqr',          'unmqr'           ),
    ('ormr2',          'ormr2',          'unmr2',          'unmr2'           ),
    ('ormtr',          'ormtr',          'unmtr',          'unmtr'           ),
    ('ort01',          'ort01',          'unt01',          'unt01'           ),
    ('plgsy',          'plgsy',          'plghe',          'plghe'           ),
    ('sbtrd',          'sbtrd',          'hbtrd',          'hbtrd'           ),
    ('sybbd',          'sybbd',          'hebbd',          'hebbd'           ),
    ('syev',           'syev',           'heev',           'heev'            ),
    ('syevd',          'syevd',          'heevd',          'heevd'           ),
    ('sygs2',          'sygs2',          'hegs2',          'hegs2'           ),
    ('sygst',          'sygst',          'hegst',          'hegst'           ),
    ('sygvd',          'sygvd',          'hegvd',          'hegvd'           ),
    ('sygvr',          'sygvr',          'hegvr',          'hegvr'           ),
    ('sygvx',          'sygvx',          'hegvx',          'hegvx'           ),
    ('syt21',          'syt21',          'het21',          'het21'           ),
    ('sytd2',          'sytd2',          'hetd2',          'hetd2'           ),
    ('sytrd',          'sytrd',          'hetrd',          'hetrd'           ),
    
    # ----- BLAS AND LAPACK, UPPERCASE, ALPHABETIC ORDER
    # COPY & PASTE THESE TO UPPERCASE BELOW AND FIX CASE.
    # USED FOR FILENAMES LACKING MAGMA_Z, ETC. PREFIX
    ('ISAMAX',         'IDAMAX',         'ICAMAX',         'IZAMAX'          ),
    ('ISAMAX',         'IDAMAX',         'ISAMAX',         'IDAMAX'          ),
    ('SAXPY',          'DAXPY',          'CAXPY',          'ZAXPY'           ),
    ('SCOPY',          'DCOPY',          'CCOPY',          'ZCOPY'           ),
    ('SGEMV',          'DGEMV',          'CGEMV',          'ZGEMV'           ),
    ('SSCAL',          'DSCAL',          'CSCAL',          'ZSCAL'           ),
    ('SSCAL',          'DSCAL',          'CSSCAL',         'ZDSCAL'          ),
    ('SSWAP',          'DSWAP',          'CSWAP',          'ZSWAP'           ),
    ('SSYMM',          'DSYMM',          'CSYMM',          'ZSYMM'           ),
    ('SSYMV',          'DSYMV',          'CSYMV',          'ZSYMV'           ),
    ('SSYR2K',         'DSYR2K',         'CSYR2K',         'ZSYR2K'          ),
    ('SSYRK',          'DSYRK',          'CSYRK',          'ZSYRK'           ),
    ('STRMM',          'DTRMM',          'CTRMM',          'ZTRMM'           ),
    ('STRMV',          'DTRMV',          'CTRMV',          'ZTRMV'           ),
    ('STRSM',          'DTRSM',          'CTRSM',          'ZTRSM'           ),
    ('STRSV',          'DTRSV',          'CTRSV',          'ZTRSV'           ),
    
    # LAPACK
    ('SBDSQR',         'DBDSQR',         'CBDSQR',         'ZBDSQR'          ),
    ('SBDT01',         'DBDT01',         'CBDT01',         'ZBDT01'          ),
    ('SCHECK',         'DCHECK',         'CCHECK',         'ZCHECK'          ),
    ('SGEBAK',         'DGEBAK',         'CGEBAK',         'ZGEBAK'          ),
    ('SGEBAL',         'DGEBAL',         'CGEBAL',         'ZGEBAL'          ),
    ('SGEBD2',         'DGEBD2',         'CGEBD2',         'ZGEBD2'          ),
    ('SGEBRD',         'DGEBRD',         'CGEBRD',         'ZGEBRD'          ),
    ('SGEEV',          'DGEEV',          'CGEEV',          'ZGEEV'           ),
    ('SGEHD2',         'DGEHD2',         'CGEHD2',         'ZGEHD2'          ),
    ('SGEHRD',         'DGEHRD',         'CGEHRD',         'ZGEHRD'          ),
    ('SGELQ2',         'DGELQ2',         'CGELQ2',         'ZGELQ2'          ),
    ('SGELQF',         'DGELQF',         'CGELQF',         'ZGELQF'          ),
    ('SGELQS',         'DGELQS',         'CGELQS',         'ZGELQS'          ),
    ('SGELS',          'DGELS',          'CGELS',          'ZGELS'           ),
    ('SGEMM',          'DGEMM',          'CGEMM',          'ZGEMM'           ),
    ('SGEQLF',         'DGEQLF',         'CGEQLF',         'ZGEQLF'          ),
    ('SGEQP3',         'DGEQP3',         'CGEQP3',         'ZGEQP3'          ),
    ('SGEQR2',         'DGEQR2',         'CGEQR2',         'ZGEQR2'          ),
    ('SGEQRF',         'DGEQRF',         'CGEQRF',         'ZGEQRF'          ),
    ('SGEQRS',         'DGEQRS',         'CGEQRS',         'ZGEQRS'          ),
    ('SGESSM',         'DGESSM',         'CGESSM',         'ZGESSM'          ),
    ('SGESV',          'DGESV',          'CGESV',          'ZGESV'           ),
    ('SGESV',          'SGESV',          'CGESV',          'CGESV'           ),
    ('SGET22',         'DGET22',         'CGET22',         'ZGET22'          ),
    ('SGETF2',         'DGETF2',         'CGETF2',         'ZGETF2'          ),
    ('SGETRF',         'DGETRF',         'CGETRF',         'ZGETRF'          ),
    ('SGETRI',         'DGETRI',         'CGETRI',         'ZGETRI'          ),
    ('SGETRL',         'DGETRL',         'CGETRL',         'ZGETRL'          ),
    ('SGETRS',         'DGETRS',         'CGETRS',         'ZGETRS'          ),
    ('SHSEQR',         'DHSEQR',         'CHSEQR',         'ZHSEQR'          ),
    ('SHST01',         'DHST01',         'CHST01',         'ZHST01'          ),
    ('SLABAD',         'DLABAD',         'SLABAD',         'DLABAD'          ),
    ('SLABRD',         'DLABRD',         'CLABRD',         'ZLABRD'          ),
    ('SLACGV',         'DLACGV',         'CLACGV',         'ZLACGV'          ),
    ('SLACPY',         'DLACPY',         'CLACPY',         'ZLACPY'          ),
    ('SLAED',          'DLAED',          'SLAED',          'DLAED'           ),
    ('SLAEX',          'DLAEX',          'SLAEX',          'DLAEX'           ),
    ('SLAGSY',         'DLAGSY',         'CLAGSY',         'ZLAGSY'          ),
    ('SLAHR',          'DLAHR',          'CLAHR',          'ZLAHR'           ),
    ('SLAMC3',         'DLAMC3',         'SLAMC3',         'DLAMC3'          ),
    ('SLAMCH',         'DLAMCH',         'SLAMCH',         'DLAMCH'          ),
    ('SLAMRG',         'DLAMRG',         'SLAMRG',         'DLAMRG'          ),
    ('SLANGE',         'DLANGE',         'CLANGE',         'ZLANGE'          ),
    ('SLANST',         'DLANST',         'CLANST',         'ZLANST'          ),
    ('SLANSY',         'DLANSY',         'CLANSY',         'ZLANSY'          ),
    ('SLANTR',         'DLANTR',         'CLANTR',         'ZLANTR'          ),
    ('SLAQPS',         'DLAQPS',         'CLAQPS',         'ZLAQPS'          ),
    ('SLARFB',         'DLARFB',         'CLARFB',         'ZLARFB'          ),
    ('SLARFG',         'DLARFG',         'CLARFG',         'ZLARFG'          ),
    ('SLARFT',         'DLARFT',         'CLARFT',         'ZLARFT'          ),
    ('SLARFX',         'DLARFX',         'CLARFX',         'ZLARFX'          ),
    ('SLARFY',         'DLARFY',         'CLARFY',         'ZLARFY'          ),
    ('SLARNV',         'DLARNV',         'CLARNV',         'ZLARNV'          ),
    ('SLARNV',         'DLARNV',         'SLARNV',         'DLARNV'          ),
    ('SLARTG',         'DLARTG',         'CLARTG',         'ZLARTG'          ),
    ('SLASCL',         'DLASCL',         'CLASCL',         'ZLASCL'          ),
    ('SLASET',         'DLASET',         'CLASET',         'ZLASET'          ),
    ('SLASWP',         'DLASWP',         'CLASWP',         'ZLASWP'          ),
    ('SLATRD',         'DLATRD',         'CLATRD',         'ZLATRD'          ),
    ('SLAUUM',         'DLAUUM',         'CLAUUM',         'ZLAUUM'          ),
    ('SPOSV',          'DPOSV',          'CPOSV',          'ZPOSV'           ),
    ('SPOSV',          'SPOSV',          'CPOSV',          'CPOSV'           ),
    ('SPOTRF',         'DPOTRF',         'CPOTRF',         'ZPOTRF'          ),
    ('SPOTRI',         'DPOTRI',         'CPOTRI',         'ZPOTRI'          ),
    ('SPOTRS',         'DPOTRS',         'CPOTRS',         'ZPOTRS'          ),
    ('SQPT01',         'DQPT01',         'CQPT01',         'ZQPT01'          ),
    ('SQRT02',         'DQRT02',         'CQRT02',         'ZQRT02'          ),
    ('SSSSSM',         'DSSSSM',         'CSSSSM',         'ZSSSSM'          ),
    ('SSTEBZ',         'DSTEBZ',         'SSTEBZ',         'DSTEBZ'          ),
    ('SSTEDC',         'DSTEDC',         'CSTEDC',         'ZSTEDC'          ),
    ('SSTEDX',         'DSTEDX',         'CSTEDX',         'ZSTEDX'          ),
    ('SSTEDX',         'DSTEDX',         'SSTEDX',         'DSTEDX'          ),
    ('SSTEIN',         'DSTEIN',         'CSTEIN',         'ZSTEIN'          ),
    ('SSTEMR',         'DSTEMR',         'CSTEMR',         'ZSTEMR'          ),
    ('SSTEQR',         'DSTEQR',         'CSTEQR',         'ZSTEQR'          ),
    ('SSTERF',         'DSTERF',         'SSTERF',         'DSTERF'          ),
    ('SSTERM',         'DSTERM',         'CSTERM',         'ZSTERM'          ),
    ('SSTT21',         'DSTT21',         'CSTT21',         'ZSTT21'          ),
    ('STREVC',         'DTREVC',         'CTREVC',         'ZTREVC'          ),
    ('STRSMPL',        'DTRSMPL',        'CTRSMPL',        'ZTRSMPL'         ),
    ('STRTRI',         'DTRTRI',         'CTRTRI',         'ZTRTRI'          ),
    ('STSQRT',         'DTSQRT',         'CTSQRT',         'ZTSQRT'          ),
    ('STSTRF',         'DTSTRF',         'CTSTRF',         'ZTSTRF'          ),
    ('SUNGESV',        'SUNGESV',        'CUNGESV',        'CUNGESV'         ),
    ('SSTEGR',         'DSTEGR',         'CSTEGR',         'ZSTEGR'          ),
    
    # ----- BLAS AND LAPACK, WHERE COMPLEX BASE NAME != REAL BASE NAME
    # BLAS, WITH PRECISION
    ('SDOT',           'DDOT',           'CDOTC',          'ZDOTC'           ),
    ('SDOT_SUB',       'DDOT_SUB',       'CDOTC_SUB',      'ZDOTC_SUB'       ),
    ('SDOT_SUB',       'DDOT_SUB',       'CDOTU_SUB',      'ZDOTU_SUB'       ),
    ('SGER',           'DGER',           'CGERC',          'ZGERC'           ),
    ('SGER',           'DGER',           'CGERU',          'ZGERU'           ),
    ('SNRM2',          'DNRM2',          'SCNRM2',         'DZNRM2'          ),
    ('SSYMM',          'DSYMM',          'CHEMM',          'ZHEMM'           ),
    ('SSYMV',          'DSYMV',          'CHEMV',          'ZHEMV'           ),
    ('SSYR2',          'DSYR2',          'CHER2',          'ZHER2'           ),
    ('SSYR2K',         'DSYR2K',         'CHER2K',         'ZHER2K'          ),
    ('SSYRK',          'DSYRK',          'CHERK',          'ZHERK'           ),
    
    # LAPACK, WITH PRECISION
    ('SLAG2D',         'DLAG2S',         'CLAG2Z',         'ZLAG2C'          ),
    ('SLAGSY',         'DLAGSY',         'CLAGHE',         'ZLAGHE'          ),
    ('SLANSY',         'DLANSY',         'CLANHE',         'ZLANHE'          ),
    ('SORG2R',         'DORG2R',         'CUNG2R',         'ZUNG2R'          ),
    ('SORGBR',         'DORGBR',         'CUNGBR',         'ZUNGBR'          ),
    ('SORGHR',         'DORGHR',         'CUNGHR',         'ZUNGHR'          ),
    ('SORGLQ',         'DORGLQ',         'CUNGLQ',         'ZUNGLQ'          ),
    ('SORGQL',         'DORGQL',         'CUNGQL',         'ZUNGQL'          ),
    ('SORGQR',         'DORGQR',         'CUNGQR',         'ZUNGQR'          ),
    ('SORGTR',         'DORGTR',         'CUNGTR',         'ZUNGTR'          ),
    ('SORM2R',         'DORM2R',         'CUNM2R',         'ZUNM2R'          ),
    ('SORMBR',         'DORMBR',         'CUNMBR',         'ZUNMBR'          ),
    ('SORMLQ',         'DORMLQ',         'CUNMLQ',         'ZUNMLQ'          ),
    ('SORMQL',         'DORMQL',         'CUNMQL',         'ZUNMQL'          ),
    ('SORMQR',         'DORMQR',         'CUNMQR',         'ZUNMQR'          ),
    ('SORMR2',         'DORMR2',         'CUNMR2',         'ZUNMR2'          ),
    ('SORMTR',         'DORMTR',         'CUNMTR',         'ZUNMTR'          ),
    ('SORT01',         'DORT01',         'CUNT01',         'ZUNT01'          ),
    ('SPLGSY',         'DPLGSY',         'CPLGHE',         'ZPLGHE'          ),
    ('SSBTRD',         'DSBTRD',         'CHBTRD',         'ZHBTRD'          ),
    ('SSYBBD',         'DSYBBD',         'CHEBBD',         'ZHEBBD'          ),
    ('SSYEV',          'DSYEV',          'CHEEV',          'ZHEEV'           ),
    ('SSYEVD',         'DSYEVD',         'CHEEVD',         'ZHEEVD'          ),
    ('SSYGS2',         'DSYGS2',         'CHEGS2',         'ZHEGS2'          ),
    ('SSYGST',         'DSYGST',         'CHEGST',         'ZHEGST'          ),
    ('SSYGVD',         'DSYGVD',         'CHEGVD',         'ZHEGVD'          ),
    ('SSYGVR',         'DSYGVR',         'CHEGVR',         'ZHEGVR'          ),
    ('SSYGVX',         'DSYGVX',         'CHEGVX',         'ZHEGVX'          ),
    ('SSYT21',         'DSYT21',         'CHET21',         'ZHET21'          ),
    ('SSYTD2',         'DSYTD2',         'CHETD2',         'ZHETD2'          ),
    ('SSYTRD',         'DSYTRD',         'CHETRD',         'ZHETRD'          ),
    
    # BLAS, WITHOUT PRECISION
    # MUST BE AFTER BLAS WITH PRECISION
    # EX: CUBLASZHEMM -> CUBLASSHEMM -> CUBLASSSYMM
    ('DOT',            'DOT',            'DOTC',           'DOTC'            ),
    ('DOT_SUB',        'DOT_SUB',        'DOTC_SUB',       'DOTC_SUB'        ),
    ('DOT_SUB',        'DOT_SUB',        'DOTU_SUB',       'DOTU_SUB'        ),
    ('GER',            'GER',            'GERC',           'GERC'            ),
    ('GER',            'GER',            'GERU',           'GERU'            ),
    ('NRM2',           'NRM2',           'CNRM2',          'ZNRM2'           ),  # DZNRM2 -> DNRM2
    ('SYMM',           'SYMM',           'HEMM',           'HEMM'            ),
    ('SYMV',           'SYMV',           'HEMV',           'HEMV'            ),
    ('SYR2',           'SYR2',           'HER2',           'HER2'            ),
    ('SYR2K',          'SYR2K',          'HER2K',          'HER2K'           ),
    ('SYRK',           'SYRK',           'HERK',           'HERK'            ),
    
    # LAPACK, WITHOUT PRECISION
    ('LAG2D',          'LAG2S',          'LAG2Z',          'LAG2C'           ),
    ('LAGSY',          'LAGSY',          'LAGHE',          'LAGHE'           ),
    ('LANSY',          'LANSY',          'LANHE',          'LANHE'           ),
    ('ORG2R',          'ORG2R',          'UNG2R',          'UNG2R'           ),
    ('ORGBR',          'ORGBR',          'UNGBR',          'UNGBR'           ),
    ('ORGHR',          'ORGHR',          'UNGHR',          'UNGHR'           ),
    ('ORGLQ',          'ORGLQ',          'UNGLQ',          'UNGLQ'           ),
    ('ORGQL',          'ORGQL',          'UNGQL',          'UNGQL'           ),
    ('ORGQR',          'ORGQR',          'UNGQR',          'UNGQR'           ),
    ('ORGTR',          'ORGTR',          'UNGTR',          'UNGTR'           ),
    ('ORM2R',          'ORM2R',          'UNM2R',          'UNM2R'           ),
    ('ORMBR',          'ORMBR',          'UNMBR',          'UNMBR'           ),
    ('ORMLQ',          'ORMLQ',          'UNMLQ',          'UNMLQ'           ),
    ('ORMQL',          'ORMQL',          'UNMQL',          'UNMQL'           ),
    ('ORMQR',          'ORMQR',          'UNMQR',          'UNMQR'           ),
    ('ORMR2',          'ORMR2',          'UNMR2',          'UNMR2'           ),
    ('ORMTR',          'ORMTR',          'UNMTR',          'UNMTR'           ),
    ('ORT01',          'ORT01',          'UNT01',          'UNT01'           ),
    ('PLGSY',          'PLGSY',          'PLGHE',          'PLGHE'           ),
    ('SBTRD',          'SBTRD',          'HBTRD',          'HBTRD'           ),
    ('SYBBD',          'SYBBD',          'HEBBD',          'HEBBD'           ),
    ('SYEV',           'SYEV',           'HEEV',           'HEEV'            ),
    ('SYEVD',          'SYEVD',          'HEEVD',          'HEEVD'           ),
    ('SYGS2',          'SYGS2',          'HEGS2',          'HEGS2'           ),
    ('SYGST',          'SYGST',          'HEGST',          'HEGST'           ),
    ('SYGVD',          'SYGVD',          'HEGVD',          'HEGVD'           ),
    ('SYGVR',          'SYGVR',          'HEGVR',          'HEGVR'           ),
    ('SYGVX',          'SYGVX',          'HEGVX',          'HEGVX'           ),
    ('SYT21',          'SYT21',          'HET21',          'HET21'           ),
    ('SYTD2',          'SYTD2',          'HETD2',          'HETD2'           ),
    ('SYTRD',          'SYTRD',          'HETRD',          'HETRD'           ),
    
    # ----- unused?
    #('stesting',       'dtesting',       'ctesting',       'ztesting'        ),
    #('SAUXILIARY',     'DAUXILIARY',     'CAUXILIARY',     'ZAUXILIARY'      ),
  ],
  
  # ------------------------------------------------------------
  # replacements applied for profiling with tau
  'tracing' :[
    # ----- Special line indicating column types
    ['plain', 'tau'],
    
    # ----- Replacements
    ('(\w+\*?)\s+(\w+)\s*\(([a-z* ,A-Z_0-9]*)\)\s*{\s+(.*)\s*#pragma tracing_start\s+(.*)\s+#pragma tracing_end\s+(.*)\s+}',
      r'\1 \2(\3){\n\4tau("\2");\5tau();\6}'),
    ('\.c','.c.tau'),
  ],
};
